// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage
// https://github.com/nightwatchjs/nightwatch-docs

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/')
      .waitForElementVisible('#main-content', 1000)
      .waitForElementVisible('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(5) > div > div > div > a > p', 1000)
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(5) > div > div > div > a')
      .assert.containsText('#main-content > div > div > div.app-container > div.app-row.inner-cont-bollo > div.form-cerca-veicolo.col-xxl-4.col-md-6.offset-xxl-1 > div.space-section > h2', 'Su avviso di scadenza')
      .click('#main-content > div > div > div.app-container > div.app-row.inner-cont-bollo > div.form-cerca-veicolo.col-xxl-4.col-md-6.offset-xxl-1 > div.space-section > a')
      .waitForElementVisible('#targa', 1000)
      .click('button[type=submit]')
      .assert.containsText('#numeroGroup > div > div', 'Il numero di riferimento dell\'avviso è obbligatorio.')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il Codice fiscale / P.IVA è obbligatorio.')
      .assert.containsText('#tipoVeicoloGroup > div > div', 'Specificare il tipo di veicolo.')
      .assert.containsText('#targaGroup > div > div', 'La targa è obbligatoria.')
      .setValue('input[id=numeroRiferimento]', '200912000372756')
      .setValue('input[id=codiceFiscale]', 'BNCLGU59B12G325Q')
      .setValue('input[id=targa]', 'ZA055GX')
      .setValue('select[id="tipoVeicolo"]', 'A')
      .click('button[type=submit]')
      .waitForElementVisible('#main-content > div > div > div.app-container > div:nth-child(3) > div > div:nth-child(1) > h2', 1000)
      .assert.containsText('#main-content > div > div > div.app-container > div:nth-child(3) > div > div:nth-child(1) > h2', 'Dati anagrafici intestatario avviso')
      .assert.containsText('#main-content > div > div > div.app-container > div:nth-child(3) > div > div:nth-child(1) > div > div.list-group > div:nth-child(1)', 'ANTONIETTA TARRICONE')
      .assert.containsText('#dati-veicolo > div > div:nth-child(1)', 'AUTOVEICOLO')
      .assert.containsText('#dati-veicolo > div > div:nth-child(2)', 'Targa: ZA055GX')
      .assert.containsText('#dati-veicolo > div > div:nth-child(3)', 'Scadenza: 04/2017')
      .assert.containsText('#dati-veicolo > div > div:nth-child(4)', 'Validità: 12 mesi')
      .assert.containsText('#dati-veicolo > div > div:nth-child(5)', 'Importo: 47,19 €')
      .assert.containsText('#dati-avviso-scadenza > div > div', '200912000372756')
      .click('button[type=submit]')
      .assert.containsText('#osservazioneScadenzaForm > div > div.error', 'Devi specificare il motivo dell\'osservazione.')
      .click('#osservazioneScadenzaForm > div > div:nth-child(1) > div > div > div > label > strong')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > h2', 500)
      .assert.containsText('#osservazioni-avv-scadenza > div > strong', 'Non sono intestatario del veicolo')
      .click('#backButton > span')
      .waitForElementVisible('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > strong', 500)
      .click('#osservazioneScadenzaForm > div > div:nth-child(2) > div > div.col-7 > div > label > strong')
      .click('button[type=submit]')
      .assert.containsText('#osservazioneScadenzaForm > div > div:nth-child(2) > div > div.col-7 > div > label > div > div', 'La data di vendita è obbligatoria.')
      .setValue('#dataVendita', '20102100')
      .assert.containsText('#osservazioneScadenzaForm > div > div:nth-child(2) > div > div.col-7 > div > label > div > div', 'La data di vendita non può essere futura.')
      .clearValue('#dataVendita')
      .setValue('#dataVendita', '12122019')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > h2', 1000)
      .assert.containsText('#main-content > div > div > div.app-container > div:nth-child(3) > div > div:nth-child(4) > div > div > div > div', 'Ho venduto il veicolo in data 12/12/2019')
      .click('#backButton > span')
      .waitForElementVisible('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > strong', 500)
      .click('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > strong') // esenzione
      .click('button[type=submit]')
      .assert.containsText('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div.error', 'Devi specificare la tipologia di esenzione.')
      .click('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div.custom-control.custom-radio > label > div:nth-child(2) > label > div > strong') // persone disabili
      .click('button[type=submit]')
      .assert.containsText('#numProtocGroup > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#dataProtocGroup > div > div', 'La data del protocollo è obbligatoria.')
      .setValue('#numProtocolloDisabili', 'AK133')
      .setValue('#dataProtocolloDisabili', '20102100')
      .assert.containsText('#dataProtocGroup > div > div', 'La data del protocollo non può essere futura.')
      .clearValue('#dataProtocolloDisabili')
      .setValue('#dataProtocolloDisabili', '12122019')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > h2', 500)
      .assert.containsText('#osservazioni-avv-scadenza > div > strong', 'Ho un\'esenzione per persone disabili')
      .assert.containsText('#osservazioni-avv-scadenza > div > div > div:nth-child(1)', 'Numero protocollo provvedimento: AK133')
      .assert.containsText('#osservazioni-avv-scadenza > div > div > div:nth-child(2)', 'Data: 12/12/2019')
      .click('#backButton > span')
      .waitForElementVisible('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > strong', 500)
      .click('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > div:nth-child(3) > label > strong') // impianto gpl
      .click('button[type=submit]')
      .assert.containsText('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > div:nth-child(3) > label > div > div', 'La data di collaudo dell\'impianto GPL/Metano è obbligatoria.')
      .setValue('#dataInstallImp', '20102100')
      .assert.containsText('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > div:nth-child(3) > label > div > div', 'La data di collaudo dell\'impianto GPL/Metano non può essere futura.')
      .clearValue('#dataInstallImp')
      .setValue('#dataInstallImp', '12122019')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > h2', 500)
      .assert.containsText('#osservazioni-avv-scadenza > div > div > div', 'Ho installato l\'impianto GPL/metano collaudato in data (allegare copia della carta di circolazione con omologa) 12/12/2019')
      .click('#backButton > span')
      .waitForElementVisible('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > div:nth-child(4) > label > div > strong', 500)
      .click('#osservazioneScadenzaForm > div > div:nth-child(5) > div > div > div > label > div:nth-child(4) > label > div > strong') // altri motivi
      .click('button[type=submit]')
      .assert.containsText('#altroMotivoGroup > div > div', 'Il motivo dell\'esenzione è obbligatorio.')
      .setValue('#esentatoAltroMotivoTesto', 'Esentato di default')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > div > strong', 500)
      .assert.containsText('#osservazioni-avv-scadenza > div > strong', 'Esenzione per altri motivi')
      .assert.containsText('#osservazioni-avv-scadenza > div > div > div > p', 'Esentato di default')
      .click('#backButton > span')
      .waitForElementVisible('#osservazioneScadenzaForm > div > div:nth-child(6) > div > div > div > label > strong', 500)
      .click('#osservazioneScadenzaForm > div > div:nth-child(6) > div > div > div > label > strong')
      .click('button[type=submit]')
      .assert.containsText('#osservazioneScadenzaForm > div > div:nth-child(6) > div > div > div > label > div > div', 'La data di trasferimento in altra regione è obbligatoria.')
      .setValue('#dataTrasfRegione', '12122019')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > div > div > div', 500)
      .assert.containsText('#osservazioni-avv-scadenza > div > div > div', 'Mi sono trasferito in altra regione in data 12/12/2019')
      .click('#backButton > span')
      .waitForElementVisible('#osservazioneScadenzaForm > div > div:nth-child(7) > div > div > div > label > strong', 500)
      .click('#osservazioneScadenzaForm > div > div:nth-child(7) > div > div > div > label > strong')
      .click('button[type=submit]')
      .assert.containsText('#osservazioneScadenzaForm > div > div:nth-child(7) > div > div > div > label > div > div', 'La data di demolizione è obbligatoria.')
      .setValue('#dataDemolizione', '12122019')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > div > div > div', 500)
      .assert.containsText('#osservazioni-avv-scadenza > div > div > div', 'Il veicolo è stato radiato per demolizione in data 12/12/2019')
      .click('#backButton > span')
      .waitForElementVisible('#osservazioneScadenzaForm > div > div:nth-child(8) > div > div > div > label > div > strong', 500)
      .click('#osservazioneScadenzaForm > div > div:nth-child(8) > div > div > div > label > div > strong')
      .setValue('select[id="tipoVeicolo"]', 'A')
      .setValue('#targa', 'AK13345')
      .setValue('#kw', '29')
      .setValue('select[id="catEuro"]', 'E0')
      .setValue('#emissCo2', '10')
      .setValue('select[id="alimentazione"]', 'G')
      .setValue('#peso', '789')
      .setValue('#assi', '8')
      .setValue('#portata', '1000')
      .setValue('#numPosti', '7')
      .click('button[type=submit]')
      .waitForElementVisible('#osservazioni-avv-scadenza > div > strong', 500)
      .assert.containsText('#osservazioni-avv-scadenza > div > strong', 'I dati tecnici non corrispondono')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(1)', 'Tipo veicolo: AUTOVEICOLO')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(2)', 'Targa: AK13345')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(3)', 'Kw: 29')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(4) > span', 'EURO 0')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(5)', 'Emissioni CO2: 10')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(6)', 'Alimentazione: GASOL')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(7)', 'Peso: 789')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(8)', 'Assi: 8')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(9)', 'Portata: 1000')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(10)', 'N° di posti: 7')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(11)', 'Rimorchiabilità: NO')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(12)', 'Sospensione Pneumatica: NO')
      .click('button[type=submit]')
      .assert.containsText('#emailGroup > div > div', 'Devi specificare almeno uno fra e-mail e numero di telefono cellulare.')
      .assert.containsText('#telefonoGroup > div > div', 'Devi specificare almeno uno fra e-mail e numero di telefono cellulare.')
      .assert.containsText('#main-content > div > div > div.app-container > div:nth-child(3) > div > form > div > div.inner-cont-2box.info-left.app-row > div > div > div > div.error', 'Il consenso all\'informativa sulla privacy è obbligatorio.')
      .setValue('#email', 'carlo.peraudo@consulenti.csi.it')
      .setValue('#telefono', '3332040510')
      .click('#privacy-label')
      .click('#main-content > div > div > div.app-container > div:nth-child(3) > div > div.action-button-wide > div.col-md-6.text-right > button')
      .waitForElementVisible('#esitoDomanda > p:nth-child(1) > strong', 1000)
      .assert.containsText('#esitoDomanda > p:nth-child(1) > strong', 'La domanda è stata registrata correttamente.')
      .assert.containsText('#esitoDomanda > p:nth-child(2) > strong', 'N° di protocollo 00000044/2020')
      .assert.containsText('#esitoDomanda > p:nth-child(3)', 'Conserva il numero per gli aggiornamenti sullo stato della pratica (controlla che sia arrivato via e-mail/SMS).')
      .assert.containsText('#dati-avviso-scadenza > div > div', '201703000008026')
      .assert.containsText('#datiVeicoloRettifica > strong', 'I dati tecnici non corrispondono')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(1)', 'Tipo veicolo: AUTOVEICOLO')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(2)', 'Targa: AK13345')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(3)', 'Kw: 29')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(4) > span', 'EURO 0')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(5)', 'Emissioni CO2: 10')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(6)', 'Alimentazione: GASOL')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(7)', 'Peso: 789')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(8)', 'Assi: 8')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(9)', 'Portata: 1000')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(10)', 'N° di posti: 7')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(11)', 'Rimorchiabilità: NO')
      .assert.containsText('#datiVeicoloRettifica > div > div:nth-child(12)', 'Sospensione Pneumatica: NO')
      .assert.containsText('#main-content > div > div > div.app-container > div:nth-child(2) > div > div:nth-child(7) > p:nth-child(2)', 'carlo.peraudo@consulenti.csi.it')
      .assert.containsText('#main-content > div > div > div.app-container > div:nth-child(2) > div > div:nth-child(7) > p:nth-child(3)', '3332040510')
      .end()
  }
}
