export const BOLLO_CALCOLO = 'calcoloBollo'
export const BOLLO_CALCOLO_RESET_STATE = 'resetStateCalcoloBollo'

export const RICEVUTA_PAGAMENTO = 'ricevutaPagam'
export const BOLLO_RICEVUTA_PDF = 'ricevutaPdfBollo'
export const PAGORATE_RICEVUTA_PDF = 'ricevutaPdfPagoRate'
export const RICEVUTA_PAGAMENTO_RESET_STATE = 'resetStateRicevuta'

export const COMMON_PRIVACY = 'informativaPrivacy'

export const INFO_VERIFICA_EMAIL = 'verificaInfoEmail'
export const INFO_RICHIESTA_ATT_EMAIL = 'richiestaAttInfoEmail'
export const INFO_ATTIVAZ_EMAIL = 'attivazInfoEmail'
export const INFO_RICHIESTA_REV_EMAIL = 'richiestaRevInfoEmail'
export const INFO_REVOCA_EMAIL = 'revocaInfoEmail'
export const INFO_VERIFICA_SMS = 'verificaInfoSms'
export const INFO_RICHIESTA_ATT_SMS = 'richiestaAttInfoSms'
export const INFO_ATTIVAZ_SMS = 'attivazInfoSms'
export const INFO_RICHIESTA_REV_SMS = 'richiestaRevInfoSms'
export const INFO_REVOCA_SMS = 'revocaInfoSms'
export const INFO_RESET_STATE = 'resetStateInfo'

export const MEMO_VERIFICA = 'verificaMemo'
export const MEMO_RICHIESTA_ATT_EMAIL = 'richiestaAttMemoEmail'
export const MEMO_ATTIVAZ_EMAIL = 'attivazMemoEmail'
export const MEMO_RICHIESTA_REV_EMAIL = 'richiestaRevMemoEmail'
export const MEMO_REVOCA_EMAIL = 'revocaMemoEmail'
export const MEMO_RICHIESTA_ATT_SMS = 'richiestaAttMemoSms'
export const MEMO_ATTIVAZ_SMS = 'attivazMemoSms'
export const MEMO_RICHIESTA_REV_SMS = 'richiestaRevMemoSms'
export const MEMO_REVOCA_SMS = 'revocaMemoSms'
export const MEMO_PRIVACY = 'scaricaPrivacyInfo'
export const MEMO_RESET_STATE = 'resetStateMemo'

export const OSS_AVV_SCADENZA_RESET_STATE = 'resetStateOssAvvScadenza'
export const AVV_SCADENZA_CERCA = 'cercaAvvisoScadenza'
export const OSS_AVV_SCADENZA_SALVA_DATI_ANAGRAFICI = 'salvaDatiAnagraficiOssAvvScadenza'
export const OSS_AVV_SCADENZA_SALVA_ATTRIBUTI = 'salvaAttributiOssAvvScadenza'
export const OSS_AVV_SCADENZA_CREA = 'creaOssAvvScadenza'
export const OSS_AVV_SCADENZA_CARICA_ALLEGATO = 'caricaAllegatoOssAvvScadenza'
export const OSS_AVV_SCADENZA_ELIMINA_ALLEGATO = 'eliminaAllegatoOssAvvScadenza'

export const OSS_AVV_ACCERTAMENTO_RESET_STATE = 'resetStateOssAvvAccertamento'
export const AVV_ACCERTAMENTO_CERCA = 'cercaAvvisoAccertamento'
export const OSS_AVV_ACC_SALVA_GRIGLIA_PAG = 'salvaGrigliaPagOssAvvAccertamento'
export const OSS_AVV_ACC_SALVA_GRIGLIA_NON_PAG = 'salvaGrigliaNonPagOssAvvAccertamento'
export const OSS_AVV_ACC_SALVA_GRIGLIA_ALTRO = 'salvaGrigliaAltroOssAvvAccertamento'
export const OSS_AVV_ACC_SALVA_NOTE = 'salvaNoteOssAvvAccertamento'
export const OSS_AVV_ACCERTAMENTO_CREA = 'creaOssAvvAccertamento'
export const OSS_AVV_ACCERTAMENTO_CARICA_ALLEGATO = 'caricaAllegatoOssAvvAccertamento'
export const OSS_AVV_ACCERTAMENTO_ELIMINA_ALLEGATO = 'eliminaAllegatoOssAvvAccertamento'

export const BOLLO_PAGO_IUV = 'pagoBolloIuv'
export const BOLLO_PAGO_RINNOVO = 'pagoBolloRinnovo'
export const BOLLO_PAGO_CONTROLLO_SCADENZA = 'pagoBolloControlloScadenza'
export const BOLLO_PAGO_SCADENZA = 'pagoBolloScadenza'
export const BOLLO_PAGO_LIST_MESE_SCADENZA = 'pagoBolloListMeseScadenza'
export const BOLLO_PAGO_LIST_ANNO_SCADENZA = 'pagoBolloListAnnoScadenza'
export const BOLLO_PAGO_LIST_VAL_SCADENZA = 'pagoBolloListValScadenza'

export const BOLLO_PAGO_RESET_STATE = 'resetStatePagoBollo'
export const BOLLO_PAGO_LIMITE_CARRELLO = 'limiteCarrelloPagoBollo'
export const BOLLO_PAGO_ELIMINA_DAL_CARRELLO = 'eliminaDalCarrelloPagoBollo'
export const BOLLO_PAGO_SALVA_RIFERIMENTI = 'salvaRiferimentiPagoBollo'
export const BOLLO_PAGO_CREA_TRANSAZIONE = 'creaTransazionePagoBollo'
export const BOLLO_PAGO_RIEPILOGO_TRANSAZIONE = 'riepilogoTransazionePagoBollo'

export const BOLLO_PAGO_RATE_CERCA = 'pagoBolloPianoRateCerca'
export const BOLLO_PAGO_RESET_STATE_RATE = 'pagoBolloRateResetState'
export const BOLLO_PAGO_SALVA_RIFERIMENTI_RATE = 'pagoBolloRateSalvaRiferimenti'
export const BOLLO_PAGO_RATE_CARRELLO = 'pagoRateCarrello'
export const BOLLO_PAGO_CREA_TRANSAZIONE_RATE = 'pagoBolloRateCreaTransazioni'
export const BOLLO_PAGO_RIEPILOGO_TRANSAZIONE_RATE = 'pagoBolloRateRiepilogoTransazioni'

export const PRATICA_ALLEGATO = 'allegatoPratica'
export const PRATICA_OSSERVAZIONE = 'osservazionePratica'
export const PRATICA_OSSERVAZIONE_MODIFICA = 'modificaOsservazionePratica'
export const PRATICA_RATEIZZAZIONE = 'rateizzazionePratica'
export const PRATICA_RATEIZZAZIONE_MODIFICA = 'modificaRateizzazionePratica'
export const PRATICA_TIPOLOGIA = 'tipologiaPratica'
export const PRATICA_RESET_STATE = 'resetStatePratica'

export const CATEGORIE_EURO_LISTA = 'listaCategorieEuro'
export const COMBUSTIBILI_LISTA = 'listaCombustibili'
export const VEICOLO_LISTA = 'listaVeicoli'
export const VEICOLO_LISTA_FILTRATA = 'listaFiltrataVeicoli'

export const PRATICA_RICHIESTA_INTESTATARIO = 'praticaRichiestaIntestatario'
export const RATEIZZAZIONE_PRATICA_ELIMINA_DAL_CARRELLO = 'eliminaDalCarrelloPraticaRateizzazione'
export const RATEIZZAZIONE_CONTROLLO_FASCE = 'controlloFasceRateizzazione'
export const PRATICA_RICHIESTA_RESET_STATE = 'resetStateRichiestaIntestatario'
export const RATEIZZA_ALLEGATO_CARICA = 'caricaAllegatoRateizza'
export const RATEIZZA_ALLEGATO_ELIMINA = 'eliminaAllegatoRateizza'
export const DATI_INTESTATARIO = 'AnagraficaDatiRateizza'
export const DATI_LEGALE_RAPPRESENTANTE = 'AnagraficaDatiLegRapprRateizza'
export const PRATICA_RAPPRESENTANTE_RESET_STATE = 'PraticaRappresentanteResetState'
export const RATEIZZAZIONE_CREA = 'PostRateizzazioneCrea'
export const RATEIZZA_ELIMINA_DAL_CARRELLO = 'RateizzazioneEliminaCarrello'

export const ADD_RATEIZZAZIONE_PRATICA = 'addRateizzazionePratica'
export const PRATICA_ACCERTAMENTO = 'cercaPraticaAccertamento'
export const PRATICA_ACCERTAMENTO_MODIFICA = 'modificaPraticaAccertamento'
export const PRATICA_DISC_RIMB = 'cercaPraticaDiscaricoRimborso'
export const PRATICA_DISC_RIMB_MODIFICA = 'modificaPraticaDiscaricoRimborso'

export const CERCA_DOMANDA_DISCARICO_RIMBORSO = 'discaricaRimborsoDomandaCrea'
export const DOMANDA_DISCARICO_RIMBORSO_RESET_STATE = 'discaricaRimborsoDomandaResetState'
export const LISTA_NUMERO_INGIUNZIONE = 'listaNumeroIngiunzione'
export const LISTA_CODICE_TRIBUTI = 'listaCodiceTributi'
export const DATI_LEGALE_RAPPRESENTANTE_DOMANDA_DISCARICO = 'AnagraficaDatiLegRapprDomDiscRimb'
export const CREAZIONE_DOMANDA_DISCARICO_RIMBORSO = 'DomandaDiscaricoRimborsoCreazione'
export const DOM_DISC_RIMB_CARICA_ALLEGATO = 'AllegatoDomandaDiscaricoRimborso'
export const DOM_DISC_RIMB_ELIMINA_ALLEGATO = 'RemoveAllegatoDomandaDiscaricoRimborso'
export const INVIO_DOMANDA_DISCARICO_RIMBORSO = 'InviaDomandaDiscaricoRimborso'

export const STAMPA_AVV_ACCERTAMENTO_CERCA_IUV = 'cercaIuvStampaAvvAccertamento'
export const STAMPA_AVV_ACCERTAMENTO_CERCA_VEICOLO = 'cercaVeicoloStampaAvvAccertamento'
export const STAMPA_AVV_ACCERTAMENTO_PDF = 'downloadPdfStampaAvvAccertamento'
export const STAMPA_AVV_ACCERTAMENTO_RESET_STATE = 'resetStateStampaAvvAccertamento'
export const STAMPA_AVV_SCADENZA_CERCA_IUV = 'cercaIuvStampaAvvScadenza'
export const STAMPA_AVV_SCADENZA_CERCA_VEICOLO = 'cercaVeicoloStampaAvvScadenza'
export const STAMPA_AVV_SCADENZA_PDF = 'downloadPdfStampaAvvScadenza'
export const STAMPA_AVV_SCADENZA_RESET_STATE = 'resetStateStampaAvvScadenza'
