export const BOLLO_CALCOLO = 'calcoloBollo'
export const BOLLO_CALCOLO_RESET_STATE = 'resetStateCalcoloBollo'

export const RICEVUTA_PAGAMENTO = 'ricevutaPagam'
export const BOLLO_RICEVUTA_PDF = 'ricevutaPdfBollo'
export const PAGORATE_RICEVUTA_PDF = 'ricevutaPdfPagoRate'
export const RICEVUTA_PAGAMENTO_RESET_STATE = 'resetStateRicevuta'
export const RICEVUTA_LIST_AUTENTICATI = 'ricevutaListAutenticati'

export const COMMON_PRIVACY = 'informativaPrivacy'
export const COMMON_MESSAGES = 'messages'
export const COMMON_GRADI_PARENTELA = 'gradiParentela'
export const COMMON_NAZIONI_ANAGRAFICA = 'nazioniAnagrafica'
export const COMMON_PROVINCE_ANAGRAFICA = 'provinceAnagrafica'
export const COMMON_COMUNI_ANAGRAFICA = 'comuniAnagrafica'
export const COMMON_COMUNI_RESIDENZA = 'comuniResidenza'
export const COMMON_PARAMETRI = 'parametri'
export const COMMON_DATI_CONTRIBUENTE = 'datiContribuente'
export const COMMON_SERVIZI = 'elencoServizi'
export const COMMON_SERVIZI_PREFERITI = 'elencoServiziPreferiti'
export const COMMON_MODIFICA_SERVIZI_PREFERITI = 'elencoModificaServiziPreferiti'
export const COMMON_ELIMINA_SERVIZI_PREFERITI = 'elencoEliminaServiziPreferiti'
export const TAB_AREA_PERSONALE = 'tabAreaPersonale'

export const INFO_VERIFICA_EMAIL = 'verificaInfoEmail'
export const INFO_RICHIESTA_ATT_EMAIL = 'richiestaAttInfoEmail'
export const INFO_ATTIVAZ_EMAIL = 'attivazInfoEmail'
export const INFO_RICHIESTA_REV_EMAIL = 'richiestaRevInfoEmail'
export const INFO_REVOCA_EMAIL = 'revocaInfoEmail'
export const INFO_VERIFICA_SMS = 'verificaInfoSms'
export const INFO_RICHIESTA_ATT_SMS = 'richiestaAttInfoSms'
export const INFO_ATTIVAZ_SMS = 'attivazInfoSms'
export const INFO_RICHIESTA_REV_SMS = 'richiestaRevInfoSms'
export const INFO_REVOCA_SMS = 'revocaInfoSms'
export const INFO_RESET_STATE = 'resetStateInfo'

export const MEMO_VERIFICA = 'verificaMemo'
export const MEMO_RICHIESTA_ATT_EMAIL = 'richiestaAttMemoEmail'
export const MEMO_ATTIVAZ_EMAIL = 'attivazMemoEmail'
export const MEMO_RICHIESTA_REV_EMAIL = 'richiestaRevMemoEmail'
export const MEMO_RICHIESTA_ATT_SMS = 'richiestaAttMemoSms'
export const MEMO_ATTIVAZ_SMS = 'attivazMemoSms'
export const MEMO_RICHIESTA_REV_SMS = 'richiestaRevMemoSms'
export const MEMO_PRIVACY = 'scaricaPrivacyInfo'
export const MEMO_RESET_STATE = 'resetStateMemo'

export const OSS_AVV_SCADENZA_RESET_STATE = 'resetStateOssAvvScadenza'
export const AVV_SCADENZA_CERCA = 'cercaAvvisoScadenza'
export const OSS_AVV_SCADENZA_SALVA_DATI_ANAGRAFICI = 'salvaDatiAnagraficiOssAvvScadenza'
export const OSS_AVV_SCADENZA_SALVA_ATTRIBUTI = 'salvaAttributiOssAvvScadenza'
export const OSS_AVV_SCADENZA_CREA = 'creaOssAvvScadenza'
export const OSS_AVV_SCADENZA_CARICA_ALLEGATO = 'caricaAllegatoOssAvvScadenza'
export const OSS_AVV_SCADENZA_ELIMINA_ALLEGATO = 'eliminaAllegatoOssAvvScadenza'
export const OSS_AVV_SCADENZA_VERIFICA_DATI_RETTIFICA = 'verificaDatiRettificaOsservazione'
export const OSS_AVV_SCADENZA_LIST_AUTENTICATI = 'ossAvvScadenzaListAutenticati'

export const OSS_AVV_ACCERTAMENTO_RESET_STATE = 'resetStateOssAvvAccertamento'
export const AVV_ACCERTAMENTO_CERCA = 'cercaAvvisoAccertamento'
export const OSS_AVV_ACC_SALVA_GRIGLIA_PAG = 'salvaGrigliaPagOssAvvAccertamento'
export const OSS_AVV_ACC_SALVA_GRIGLIA_NON_PAG = 'salvaGrigliaNonPagOssAvvAccertamento'
export const OSS_AVV_ACC_SALVA_GRIGLIA_ALTRO = 'salvaGrigliaAltroOssAvvAccertamento'
export const OSS_AVV_ACC_SALVA_NOTE = 'salvaNoteOssAvvAccertamento'
export const OSS_AVV_ACCERTAMENTO_CREA = 'creaOssAvvAccertamento'
export const OSS_AVV_ACCERTAMENTO_CARICA_ALLEGATO = 'caricaAllegatoOssAvvAccertamento'
export const OSS_AVV_ACCERTAMENTO_ELIMINA_ALLEGATO = 'eliminaAllegatoOssAvvAccertamento'
export const OSS_AVV_ACCERTAMENTO_LIST_AUTENTICATI = 'ossAvvAccertamentoListAutenticati'

export const AVV_BONARIO_CERCA = 'cercaAvvisoBonario'
export const OSS_AVV_BONARIO_RESET_STATE = 'resetStateOssAvvBonario'
export const OSS_AVV_BONARIO_SALVA_GRIGLIA_PAG = 'salvaGrigliaPagOssAvvBonario'
export const OSS_AVV_BONARIO_SALVA_GRIGLIA_NON_PAG = 'salvaGrigliaNonPagOssAvvBonario'
export const OSS_AVV_BONARIO_SALVA_GRIGLIA_ALTRO = 'salvaGrigliaAltroOssAvvBonario'
export const OSS_AVV_BONARIO_SALVA_NOTE = 'salvaNoteOssAvvBonario'
export const OSS_AVV_BONARIO_CREA = 'creaOssAvvBonario'
export const OSS_AVV_BONARIO_CARICA_ALLEGATO = 'caricaAllegatoOssAvvBonario'
export const OSS_AVV_BONARIO_ELIMINA_ALLEGATO = 'eliminaAllegatoOssAvvBonario'
export const OSS_AVV_BONARIO_LIST_AUTENTICATI = 'ossAvvBonarioListAutenticati'

export const BOLLO_PAGO_IUV = 'pagoBolloIuv'
export const BOLLO_PAGO_RINNOVO = 'pagoBolloRinnovo'
export const BOLLO_PAGO_CONTROLLO_SCADENZA = 'pagoBolloControlloScadenza'
export const BOLLO_PAGO_SCADENZA = 'pagoBolloScadenza'
export const BOLLO_PAGO_LIST_MESE_SCADENZA = 'pagoBolloListMeseScadenza'
export const BOLLO_PAGO_LIST_ANNO_SCADENZA = 'pagoBolloListAnnoScadenza'
export const BOLLO_PAGO_LIST_VAL_SCADENZA = 'pagoBolloListValScadenza'

export const BOLLO_PAGO_RESET_STATE = 'resetStatePagoBollo'
export const BOLLO_PAGO_LIMITE_CARRELLO = 'limiteCarrelloPagoBollo'
export const BOLLO_PAGO_ELIMINA_DAL_CARRELLO = 'eliminaDalCarrelloPagoBollo'
export const BOLLO_PAGO_SALVA_RIFERIMENTI = 'salvaRiferimentiPagoBollo'
export const BOLLO_PAGO_CREA_TRANSAZIONE = 'creaTransazionePagoBollo'
export const BOLLO_PAGO_RIEPILOGO_TRANSAZIONE = 'riepilogoTransazionePagoBollo'

export const BOLLO_PAGO_RATE_CERCA = 'pagoBolloPianoRateCerca'
export const BOLLO_PAGO_RESET_STATE_RATE = 'pagoBolloRateResetState'
export const BOLLO_PAGO_SALVA_RIFERIMENTI_RATE = 'pagoBolloRateSalvaRiferimenti'
export const BOLLO_PAGO_RATE_CARRELLO = 'pagoRateCarrello'
export const BOLLO_PAGO_CREA_TRANSAZIONE_RATE = 'pagoBolloRateCreaTransazioni'
export const BOLLO_PAGO_RIEPILOGO_TRANSAZIONE_RATE = 'pagoBolloRateRiepilogoTransazioni'

export const PRATICA_ALLEGATO = 'allegatoPratica'
export const PRATICA_OSSERVAZIONE = 'osservazionePratica'
export const PRATICA_OSSERVAZIONE_MODIFICA = 'modificaOsservazionePratica'
export const PRATICA_RATEIZZAZIONE = 'rateizzazionePratica'
export const PRATICA_RATEIZZAZIONE_MODIFICA = 'modificaRateizzazionePratica'
export const PRATICA_TIPOLOGIA = 'tipologiaPratica'
export const PRATICA_RESET_STATE = 'resetStatePratica'

export const CATEGORIE_EURO_LISTA = 'listaCategorieEuro'
export const COMBUSTIBILI_LISTA = 'listaCombustibili'
export const VEICOLO_LISTA = 'listaVeicoli'
export const VEICOLO_LISTA_FILTRATA = 'listaFiltrataVeicoli'

export const PRATICA_RICHIESTA_INTESTATARIO = 'praticaRichiestaIntestatario'
export const RATEIZZAZIONE_PRATICA_ELIMINA_DAL_CARRELLO = 'eliminaDalCarrelloPraticaRateizzazione'
export const RATEIZZAZIONE_CONTROLLO_FASCE = 'controlloFasceRateizzazione'
export const PRATICA_RICHIESTA_RESET_STATE = 'resetStateRichiestaIntestatario'
export const RATEIZZA_ALLEGATO_CARICA = 'caricaAllegatoRateizza'
export const RATEIZZA_ALLEGATO_ELIMINA = 'eliminaAllegatoRateizza'
export const DATI_INTESTATARIO = 'AnagraficaDatiRateizza'
export const DATI_LEGALE_RAPPRESENTANTE = 'AnagraficaDatiLegRapprRateizza'
export const SCELTA_RATA_UTENTE = 'SceltaRataUtente'
export const PRATICA_RAPPRESENTANTE_RESET_STATE = 'PraticaRappresentanteResetState'
export const RATEIZZAZIONE_CREA = 'PostRateizzazioneCrea'
export const RATEIZZAZIONE_VALIDA = 'PostRateizzazioneValida'
export const RATEIZZAZIONE_ELIMINA_DAL_CARRELLO = 'RateizzazioneEliminaCarrello'
export const RATEIZZAZIONE_LIST_AUTENTICATI = 'RateizzazioneListAutenticati'

export const ADD_RATEIZZAZIONE_PRATICA = 'addRateizzazionePratica'
export const PRATICA_ACCERTAMENTO = 'cercaPraticaAccertamento'
export const PRATICA_ACCERTAMENTO_MODIFICA = 'modificaPraticaAccertamento'
export const PRATICA_DISC_RIMB = 'cercaPraticaDiscaricoRimborso'
export const PRATICA_DISC_RIMB_MODIFICA = 'modificaPraticaDiscaricoRimborso'

export const PRATICA_BONARIO = 'cercaPraticaBonario'
export const PRATICA_BONARIO_MODIFICA = 'modificaPraticaBonario'

export const CERCA_DOMANDA_DISCARICO_RIMBORSO = 'discaricaRimborsoDomandaCrea'
export const DOMANDA_DISCARICO_RIMBORSO_RESET_STATE = 'discaricaRimborsoDomandaResetState'
export const LISTA_NUMERO_INGIUNZIONE = 'listaNumeroIngiunzione'
export const LISTA_CODICE_TRIBUTI = 'listaCodiceTributi'
export const DATI_LEGALE_RAPPRESENTANTE_DOMANDA_DISCARICO = 'AnagraficaDatiLegRapprDomDiscRimb'
export const CREAZIONE_DOMANDA_DISCARICO_RIMBORSO = 'DomandaDiscaricoRimborsoCreazione'
export const DOM_DISC_RIMB_CARICA_ALLEGATO = 'AllegatoDomandaDiscaricoRimborso'
export const DOM_DISC_RIMB_ELIMINA_ALLEGATO = 'RemoveAllegatoDomandaDiscaricoRimborso'
export const INVIO_DOMANDA_DISCARICO_RIMBORSO = 'InviaDomandaDiscaricoRimborso'

export const STAMPA_AVV_ACCERTAMENTO_CERCA_IUV = 'cercaIuvStampaAvvAccertamento'
export const STAMPA_AVV_ACCERTAMENTO_CERCA_VEICOLO = 'cercaVeicoloStampaAvvAccertamento'
export const STAMPA_AVV_ACCERTAMENTO_PDF = 'downloadPdfStampaAvvAccertamento'
export const STAMPA_AVV_ACCERTAMENTO_RESET_STATE = 'resetStateStampaAvvAccertamento'
export const STAMPA_OSS_AVV_ACCERTAMENTO_LIST_AUTENTICATI = 'listAuthStampaAvvAcc'
export const STAMPA_LETTERA_AVV_ACCERTAMENTO_PDF = 'downloadPdfLettersAvvAccertamento'
export const STAMPA_AVV_SCADENZA_CERCA_IUV = 'cercaIuvStampaAvvScadenza'
export const STAMPA_AVV_SCADENZA_CERCA_VEICOLO = 'cercaVeicoloStampaAvvScadenza'
export const STAMPA_AVV_SCADENZA_PDF = 'downloadPdfStampaAvvScadenza'
export const STAMPA_AVV_SCADENZA_RESET_STATE = 'resetStateStampaAvvScadenza'

export const STAMPA_PIANO_RATEIZZAZIONE_CERCA = 'stampaPianoRateizzazioneCerca'
export const STAMPA_PIANO_RATEIZZAZIONE_PDF = 'downloadPdfPianoRateizzazione'
export const STAMPA_PIANO_RATEIZZAZIONE_RESET_STATE = 'stampaPianoRateizzazioneResetState'

export const ESENZIONI_DISABILI_CONTRIBUENTI = 'esenzioniDisabiliContribuenti'
export const ESENZIONI_DISABILI_VEICOLI = 'esenzioniDisabiliVeicoli'
export const ESENZIONI_DISABILI_CARICA_ALLEGATO = 'esenzioniDisabiliVeicoliCaricaAllegato'
export const ESENZIONI_DISABILI_ELIMINA_ALLEGATO = 'esenzioniDisabiliVeicoliEliminaaAllegato'
export const ESENZIONI_DISABILI_CREA = 'esenzioniEsenzioniDisabiliCrea'
export const ESENZIONI_DISABILI_RESET_STATE = 'esenzioniEsenzioniResetState'

export const PRATICA_RESET_STATE_AUTH = 'praticaResetStateAuth'
export const PRATICA_ALLEGATO_AUTH = 'praticaAllegatoAuth'
export const PRATICA_ESENZIONI_DISABILI = 'praticaEsenzioniDisabili'
export const PRATICA_RESTITUZIONE_TASSA = 'praticaRestituzioneTassa'
export const PRATICA_ESENZIONI_DISABILI_MODIFICA = 'praticaEsenzioniDisabiliModifica'
export const PRATICA_COMUNICAZIONI_LIST_AUTENTICATI = 'praticaComunicazioniListAutenticati'

export const RESTITUZIONI_TASSA_CONTRIBUENTI = 'restituzioniTassaContribuenti'
export const RESTITUZIONI_TASSA_VEICOLI = 'restituzioniTassaVeicoli'
export const RESTITUZIONI_TASSA_CARICA_ALLEGATO = 'restituzioniTassaVeicoliCaricaAllegato'
export const RESTITUZIONI_TASSA_ELIMINA_ALLEGATO = 'restituzioniTassaVeicoliEliminaaAllegato'
export const RESTITUZIONI_TASSA_CREA = 'restituzioniTassaCrea'
export const RESTITUZIONI_TASSA_RESET_STATE = 'restituzioniTassaResetState'
export const RESTITUZIONI_TASSA_VEICOLI_VERSAMENTI = 'restituzioniTassaVeicoliVersamenti'
export const PRATICA_RESTITUZIONI_TASSA_MODIFICA = 'praticarestituzioniTassaModifica'

export const VISURE_CONTRIBUENTE = 'visureContribuente'
export const DETTAGLIO_VEICOLO_VISURE_KEY = 'dettaglioVeicoloVisureKey'
export const DETTAGLIO_VEICOLO_VISURE = 'dettaglioVeicoloVisure'
export const DETTAGLIO_VEICOLO_SCELTO = 'dettaglioVeicoloScelto'
export const VISURE_DETTAGLIO_VEICOLO_SCELTO_RESET_STATE = 'visureDettaglioVeicoloSceltoResetState'

export const UTENTE_CARICA_IDENTITA = 'caricaIdentitaUtente'
export const UTENTE_SALVA_IDENTITA = 'salvaIdentitaUtente'
export const UTENTE_CARICA = 'caricaUtente'

export const UTENTE_LOCALHOST_LOGIN = 'localhostLoginUtente'
export const UTENTE_LOCALHOST_LOGOUT = 'localhostLogoutUtente'

export const NOTIFICHE_LISTA_NON_LETTE = 'notificheLista'
export const NOTIFICHE_LISTA_LETTE = 'notificheListaLette'
export const DETTAGLIO_NOTIFICA = 'dettaglioNotifica'
export const MODIFICA_NOTIFICA = 'modificaNotifica'
export const ELIMINA_NOTIFICA = 'eliminaNotifica'
export const NOTIFICHE_RESET_STATE = 'notificheResetState'
