export const SET_INFOBOLLO_EMAIL = 'setInfobolloEmail'
export const SET_INFOBOLLO_SMS = 'setInfobolloSms'
export const INITIAL_STATE_INFOBOLLO = 'initialInfobollo'

export const SET_MEMOBOLLO = 'setMemobollo'
export const UPD_MEMOBOLLO_EMAIL = 'updMemobolloEmail'
export const UPD_MEMOBOLLO_SMS = 'updMemobolloSms'
export const INITIAL_STATE_MEMOBOLLO = 'initialStateMemobollo'

export const SET_AVVISO_SCADENZA = 'setAvvisoScadenza'
export const UPD_DATI_ANAGRAFICI_OSS_AVV_SCADENZA = 'updDatiAnagraficiOssAvvScadenza'
export const UPD_ATTRIB_OSS_AVV_SCADENZA = 'updAttributiOssAvvScadenza'
export const ADD_ALLEGATO_OSS_AVV_SCADENZA = 'addAllegatoOssAvvScadenza'
export const REM_ALLEGATO_OSS_AVV_SCADENZA = 'remAllegatoOssAvvScadenza'
export const INIT_STATE_OSS_AVV_SCADENZA = 'initialStateOssAvvScadenza'

export const SET_AVVISO_ACCERTAMENTO = 'setAvvisoAccertamento'
export const UPD_GRIGLIA_PAG_OSS_AVV_ACC = 'updGrigliaPagOssAvvAccertamento'
export const UPD_GRIGLIA_NON_PAG_OSS_AVV_ACC = 'updGrigliaNonPagOssAvvAccertamento'
export const UPD_GRIGLIA_ALTRO_OSS_AVV_ACC = 'updGrigliaAltroOssAvvAccertamento'
export const UPD_NOTE_OSS_AVV_ACC = 'updNoteOssAvvAccertamento'
export const SET_OSS_AVV_ACCERTAMENTO_CREATA = 'avvisoAccertamentoCreata'
export const ADD_ALLEGATO_OSS_AVV_ACCERTAMENTO = 'addAllegatoOssAvvAccertamento'
export const REM_ALLEGATO_OSS_AVV_ACCERTAMENTO = 'remAllegatoOssAvvAccertamento'
export const INIT_STATE_OSS_AVV_ACCERTAMENTO = 'initialStateOssAvvAccertamento'
export const INIT_STATE_OSS_AVV_ACC_NONPAGATO = 'initialStateAvvAccNonPagato'
export const INIT_STATE_OSS_AVV_ACC_PAGATO = 'initialStateAvvAccPagato'
export const INIT_STATE_OSS_AVV_ACC_ALTRO = 'initialStateAvvAccAltro'

export const SET_BOLLO_CALCOLO = 'setCalcoloBollo'
export const INITIAL_STATE_BOLLO_CALCOLO = 'initialStateCalcoloBollo'

export const SET_RICEVUTA_PAGAMENTO = 'setRicevutaPagamento'
export const INITIAL_STATE_RICEVUTA_PAGAMENTO = 'initialStateRicevutaPagamento'

export const SET_VERIFICA_PRATICA = 'setVerificaPratica'
export const INITIAL_STATE_VERIFICA_PRATICA = 'initialStateVerificaPratica'

export const MAX_CARRELLO = 'setLimiteCarrello'
export const ADD_PAGAMENTO_BOLLO = 'addPagamentoBollo'
export const REM_PAGAMENTO_BOLLO = 'remPagamentoBollo'
export const UPD_RIF_PAGAMENTO_BOLLO = 'upfRiferimentiPagamentoBollo'
export const INITIAL_STATE_PAGAMENTO_BOLLO = 'initialStatePagamentoBollo'

export const ADD_PAGAMENTO_RATE = 'addPagamentoRate'
export const UPD_PAGO_RATE_CARRELLO = 'updPagoRateCarrello'
export const INITIAL_STATE_PAGAMENTO_RATA = 'addRataScelta'

export const ADD_RATEIZZAZIONE_PRATICA = 'addRateizzazionePratica'
export const FASCE_RATEIZZAZIONE = 'rateizzazioneFasce'
export const ADD_ALLEGATO_RATEIZZA = 'RateizzaAllegatoAdd'
export const REM_ALLEGATO_RATEIZZA = 'RateizzaAllegatoRem'
export const ADD_DATI_INTESTATARIO = 'IntestatarioDatiAdd'
export const ADD_DATI_LEGALE_RAPPRESENTANTE = 'LegaleRapprDatiAdd'
export const RAPPRESENTANTE_RESET_STATE = 'RappresentanteResetState'
export const REM_PROTOCOLLO_RATEIZZA = 'RemProtocolloRateizzazione'
export const INITIAL_STATE_RATEIZZAZIONE = 'initialStateRateizzazione'

export const ADD_ANAGRAFICA_DISCARICO_RIMBORSO = 'AnagraficaDiscaricoRimborsoAdd'
export const INITIAL_STATE_DOMANDA_DISCARICO_RIMBORSO = 'AnagraficaDiscaricoRimborsoInitialState'
export const ADD_DATI_LEGALE_RAPPRESENTANTE_DOMANDA_DISCARICO = 'LegaleRapprDomDiscRimbDatiAdd'
export const ADD_DOMANDA_DISCARICO_RIMBORSO = 'DomandaDiscaricoRimborsoAdd'
export const ADD_ALLEGATO_DOM_DISC_RIMB = 'AddAllegatoDomandaDiscaricoRimborso'
export const RESPONSE_DOMANDA_DISCARICO_RIMBORSO = 'ResponseDomandaDiscaricoRimborso'
export const REMOVE_ALLEGATO_DOM_DISC_RIMB = 'RemoveAllegatoDomandaDiscaricoRimborso'

export const ADD_STAMPA_AVV_ACCERTAMENTO = 'addStampaAvvAccertamento'
export const INITIAL_STATE_STAMPA_AVV_ACCERTAMENTO = 'initialStateStampaAvvAccertamento'
export const ADD_STAMPA_AVV_SCADENZA = 'addStampaAvvScadenza'
export const INITIAL_STATE_STAMPA_AVV_SCADENZA = 'initialStateStampaAvvScadenza'

export const SET_CATEGORIE_EURO_LISTA = 'setCategorieEuroLista'
export const SET_COMBUSTIBILI_LISTA = 'setCombustibiliLista'
export const SET_VEICOLO_LISTA_FILTRATA = 'setVeicoliListaFiltrata'
