export const SET_INFOBOLLO_EMAIL = 'setInfobolloEmail'
export const SET_INFOBOLLO_SMS = 'setInfobolloSms'
export const INITIAL_STATE_INFOBOLLO = 'initialInfobollo'

export const SET_MEMOBOLLO = 'setMemobollo'
export const UPD_MEMOBOLLO_EMAIL = 'updMemobolloEmail'
export const UPD_MEMOBOLLO_SMS = 'updMemobolloSms'
export const INITIAL_STATE_MEMOBOLLO = 'initialStateMemobollo'

export const SET_AVVISO_SCADENZA = 'setAvvisoScadenza'
export const UPD_DATI_ANAGRAFICI_OSS_AVV_SCADENZA = 'updDatiAnagraficiOssAvvScadenza'
export const UPD_ATTRIB_OSS_AVV_SCADENZA = 'updAttributiOssAvvScadenza'
export const ADD_ALLEGATO_OSS_AVV_SCADENZA = 'addAllegatoOssAvvScadenza'
export const REM_ALLEGATO_OSS_AVV_SCADENZA = 'remAllegatoOssAvvScadenza'
export const INIT_STATE_OSS_AVV_SCADENZA = 'initialStateOssAvvScadenza'
export const UPD_VERIFICA_DATI_RETTIFICA = 'updVerificaDatiRettifica'

export const SET_AVVISO_ACCERTAMENTO = 'setAvvisoAccertamento'
export const UPD_GRIGLIA_PAG_OSS_AVV_ACC = 'updGrigliaPagOssAvvAccertamento'
export const UPD_GRIGLIA_NON_PAG_OSS_AVV_ACC = 'updGrigliaNonPagOssAvvAccertamento'
export const UPD_GRIGLIA_ALTRO_OSS_AVV_ACC = 'updGrigliaAltroOssAvvAccertamento'
export const UPD_NOTE_OSS_AVV_ACC = 'updNoteOssAvvAccertamento'
export const SET_OSS_AVV_ACCERTAMENTO_CREATA = 'avvisoAccertamentoCreata'
export const ADD_ALLEGATO_OSS_AVV_ACCERTAMENTO = 'addAllegatoOssAvvAccertamento'
export const REM_ALLEGATO_OSS_AVV_ACCERTAMENTO = 'remAllegatoOssAvvAccertamento'
export const INIT_STATE_OSS_AVV_ACCERTAMENTO = 'initialStateOssAvvAccertamento'
export const INIT_STATE_OSS_AVV_ACC_NONPAGATO = 'initialStateAvvAccNonPagato'
export const INIT_STATE_OSS_AVV_ACC_PAGATO = 'initialStateAvvAccPagato'
export const INIT_STATE_OSS_AVV_ACC_ALTRO = 'initialStateAvvAccAltro'

export const SET_AVVISO_BONARIO = 'setAvvisoBonario'
export const UPD_GRIGLIA_PAG_OSS_AVV_BONARIO = 'updGrigliaPagOssAvvBonario'
export const UPD_GRIGLIA_NON_PAG_OSS_AVV_BONARIO = 'updGrigliaNonPagOssAvvBonario'
export const UPD_GRIGLIA_ALTRO_OSS_AVV_BONARIO = 'updGrigliaAltroOssAvvBonario'
export const UPD_NOTE_OSS_AVV_BONARIO = 'updNoteOssAvvBonario'
export const INIT_STATE_OSS_AVV_BONARIO = 'initialStateOssAvvBonario'
export const INIT_STATE_OSS_AVV_BONARIO_PAGATO = 'initialStateAvvBonarioPagato'
export const INIT_STATE_OSS_AVV_BONARIO_NONPAGATO = 'initialStateAvvBonarioNonPagato'
export const INIT_STATE_OSS_AVV_BONARIO_ALTRO = 'initialStateAvvBonarioAltro'
export const ADD_ALLEGATO_OSS_AVV_BONARIO = 'addAllegatoOssAvvBonario'
export const REM_ALLEGATO_OSS_AVV_BONARIO = 'remAllegatoOssAvvBonario'

export const SET_BOLLO_CALCOLO = 'setCalcoloBollo'
export const INITIAL_STATE_BOLLO_CALCOLO = 'initialStateCalcoloBollo'

export const SET_RICEVUTA_PAGAMENTO = 'setRicevutaPagamento'
export const INITIAL_STATE_RICEVUTA_PAGAMENTO = 'initialStateRicevutaPagamento'
export const UPD_RICEVUTA_LIST_AUTENTICATI = 'updRicevutaListauth'

export const SET_VERIFICA_PRATICA = 'setVerificaPratica'
export const INITIAL_STATE_VERIFICA_PRATICA = 'initialStateVerificaPratica'

export const MAX_CARRELLO = 'setLimiteCarrello'
export const ADD_PAGAMENTO_BOLLO = 'addPagamentoBollo'
export const REM_PAGAMENTO_BOLLO = 'remPagamentoBollo'
export const UPD_RIF_PAGAMENTO_BOLLO = 'upfRiferimentiPagamentoBollo'
export const INITIAL_STATE_PAGAMENTO_BOLLO = 'initialStatePagamentoBollo'

export const ADD_PAGAMENTO_RATE = 'addPagamentoRate'
export const UPD_PAGO_RATE_CARRELLO = 'updPagoRateCarrello'
export const INITIAL_STATE_PAGAMENTO_RATA = 'addRataScelta'

export const ADD_RATEIZZAZIONE_PRATICA = 'addRateizzazionePratica'
export const FASCE_RATEIZZAZIONE = 'rateizzazioneFasce'
export const ADD_ALLEGATO_RATEIZZA = 'RateizzaAllegatoAdd'
export const REM_ALLEGATO_RATEIZZA = 'RateizzaAllegatoRem'
export const ADD_DATI_INTESTATARIO = 'IntestatarioDatiAdd'
export const ADD_DATI_LEGALE_RAPPRESENTANTE = 'LegaleRapprDatiAdd'
export const RAPPRESENTANTE_RESET_STATE = 'RappresentanteResetState'
export const ADD_SCELTA_RATA_UTENTE = 'AddSceltaRataUtente'
export const REM_PROTOCOLLO_RATEIZZA = 'RemProtocolloRateizzazione'
export const INITIAL_STATE_RATEIZZAZIONE = 'initialStateRateizzazione'
export const UPD_RATEIZZAZIONE_LIST_AUTENTICATI = 'updRateizzazioneListAutenticati'

export const UPD_PRATICA_COMUNICAZIONI_LIST_AUTENTICATI = 'updPraticaComunicazioniListAutenticati'
export const UPD_OSS_AVV_SCADENZA_LIST_AUTENTICATI = 'updOssScadenzaListAutenticati'
export const UPD_OSS_AVV_ACCERTAMENTO_LIST_AUTENTICATI = 'updOssAccertamentoListAutenticati'
export const UPD_OSS_AVV_BONARIO_LIST_AUTENTICATI = 'updOssBonarioListAutenticati'

export const ADD_ANAGRAFICA_DISCARICO_RIMBORSO = 'AnagraficaDiscaricoRimborsoAdd'
export const INITIAL_STATE_DOMANDA_DISCARICO_RIMBORSO = 'AnagraficaDiscaricoRimborsoInitialState'
export const ADD_DATI_LEGALE_RAPPRESENTANTE_DOMANDA_DISCARICO = 'LegaleRapprDomDiscRimbDatiAdd'
export const ADD_DOMANDA_DISCARICO_RIMBORSO = 'DomandaDiscaricoRimborsoAdd'
export const ADD_ALLEGATO_DOM_DISC_RIMB = 'AddAllegatoDomandaDiscaricoRimborso'
export const RESPONSE_DOMANDA_DISCARICO_RIMBORSO = 'ResponseDomandaDiscaricoRimborso'
export const REMOVE_ALLEGATO_DOM_DISC_RIMB = 'RemoveAllegatoDomandaDiscaricoRimborso'

export const ADD_STAMPA_AVV_ACCERTAMENTO = 'addStampaAvvAccertamento'
export const INITIAL_STATE_STAMPA_AVV_ACCERTAMENTO = 'initialStateStampaAvvAccertamento'
export const ADD_STAMPA_AVV_SCADENZA = 'addStampaAvvScadenza'
export const INITIAL_STATE_STAMPA_AVV_SCADENZA = 'initialStateStampaAvvScadenza'
export const UPD_STAMPA_OSS_AVV_ACCERTAMENTO_LIST_AUTENTICATI = 'updOssAvvListAuth'

export const ADD_STAMPA_PIANO_RATEIZZAZIONE = 'addStampaPianoRateizzazione'

export const SET_CATEGORIE_EURO_LISTA = 'setCategorieEuroLista'
export const SET_COMBUSTIBILI_LISTA = 'setCombustibiliLista'
export const SET_VEICOLO_LISTA_FILTRATA = 'setVeicoliListaFiltrata'

export const SET_ESENZIONI_DISABILI = 'setEsenzioniDisabili'
export const SET_ESENZIONI_DISABILI_VEICOLI = 'setEsenzioniDisabiliVeicoli'
export const SET_ESENZIONI_DISABILI_CONTRIBUENTI = 'setEsenzioniDisabiliContribuenti'
export const INIT_STATE_ESENZIONI_DISABILI = 'initStateEsenzioniDisabili'
export const ADD_ALLEGATO_ESENZIONI_DISABILI = 'addAllegatoEsenzioniDisabili'
export const REM_ALLEGATO_ESENZIONI_DISABILI = 'remAllegatoEsenzioniDisabili'
export const SET_ESENZIONI_DISABILI_RESPONSE = 'setEsenzioniDisabiliResponse'

export const INITIAL_STATE_CONSULTA_PRATICA_AUTH = 'initialStateConsultaPraticaAuth'
export const SET_CONSULTA_PRATICA_AUTH = 'setConsultaPraticaAuth'

export const SET_RESTITUZIONI_TASSA = 'setRestituzioniTassa'
export const SET_RESTITUZIONI_TASSA_RESPONSE = 'setRestituzioniTassaresponse'
export const SET_RESTITUZIONI_TASSA_VEICOLI = 'setRestituzioniTassaVeicoli'
export const SET_RESTITUZIONI_TASSA_CONTRIBUENTI = 'setRestituzioniTassaContribuentiEsenzioni'
export const INIT_STATE_RESTITUZIONI_TASSA = 'initStateRestituzioniTassa'
export const ADD_ALLEGATO_RESTITUZIONI_TASSA = 'addAllegatoRestituzioniTassa'
export const REM_ALLEGATO_RESTITUZIONI_TASSA = 'remAllegatoRestituzioniTassa'
export const SET_RESTITUZIONI_TASSA_TELEFONO = 'setRestituzioniTassaTelefono'
export const SET_RESTITUZIONI_TASSA_EMAIL = 'setRestituzioniTassaEmail'
export const SET_RESTITUZIONI_TASSA_VEICOLI_VERSAMENTI_ELENCO = 'setResetRestituzioniTassaVeicoliVersamentiElenco'
export const SET_ADD_RESTITUZIONI_TASSA_VEICOLI_VERSAMENTI_ELENCO = 'setAddRestituzioniTassaVeicoliVersamentiElenco'
export const SET_RESET_RESTITUZIONI_TASSA_VEICOLI_VERSAMENTI_ELENCO = 'resetRestituzioniTassaVeicoliVersamentiElenco'

export const SET_VISURE_ELENCO_VEICOLI = 'setVisureElencoVeicoli'
export const SET_VISURE_KEY = 'setVisureKey'
export const SET_DETTAGLIO_VEICOLO_VISURE = 'setDettaglioVeicoloVisure'
export const SET_DETTAGLIO_VEICOLO_SCELTO = 'setDettaglioVeicoloScelto'
export const INITIAL_STATE_VISURE_DETTAGLIO_VEICOLO_SCELTO = 'initialStateVisureDettaglioVeicoloScelto'

export const SET_COMMON_GRADI_PARENTELA = 'setGradiParentelaCommon'
export const SET_COMMON_NAZIONI_ANAGRAFICA = 'setNazioniCommon'
export const SET_COMMON_PROVINCE_ANAGRAFICA = 'setProvinceCommon'
export const SET_COMMON_COMUNI_ANAGRAFICA = 'setComuniAnagraficaCommon'
export const SET_COMMON_COMUNI_RESIDENZA = 'setComuniResidenzaCommon'
export const SET_COMMON_MESSAGES = 'setMessages'
export const SET_COMMON_PARAMETRI = 'setParametri'
export const SET_COMMON_DATI_CONTRIBUENTE = 'setDatiContribuente'
export const SET_COMMON_SERVIZI = 'setCommonServizi'
export const SET_COMMON_SERVIZI_PREFERITI = 'setCommonServiziPreferiti'
export const RIMUOVI_COMMON_SERVIZI_PREFERITI = 'rimoviCommonServiziPreferiti'
export const SET_TAB_AREA_PERSONALE = 'setTabAreaPersonale'

export const SET_IDENTITA_UTENTE = 'setIdentitaUtente'
export const SET_RESIDENT = 'setResident'

export const SET_LOCALHOST_LOGIN = 'setLocalhostLogin'
export const PURGE_LOCALHOST_LOGIN = 'purgeLocalhostLogin'

export const INITIAL_STATE_NOTIFICHE = 'initialStateNotifiche'
export const SET_NOTIFICHE_LISTA_NON_LETTE = 'setNotificheListaNonLette'
export const SET_NOTIFICHE_LISTA_LETTE = 'setNotificheListaLette'
export const SET_DETTAGLIO_NOTIFICA = 'setdDettaglioNotifica'
export const RIMUOVI_NOTIFICA = 'rimuoviNotifica'
