module.exports = {
  'default e2e tests': function (browser) {
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/')
      .waitForElementVisible('#app', 1000)
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(1) > div > div > a > h4', 'Memobollo')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(2) > div > div > div > a > h4', 'Pagamenti online')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(3) > div > div > a > h4', 'Scarica la ricevuta di un pagamento')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(4) > div > div > a > h4', 'Calcola il bollo')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(5) > div > div > div > a > h4', 'Fai un\'osservazione su')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(6) > div > div > a > h4', 'Consulta una pratica')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(7) > div > div > a > h4', 'Chiedi la rateizzazione')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(8) > div > div > a > h4', 'Fai domanda di discarico o rimborso di cartella o ingiunzione di pagamento')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(9) > div > div > a > h4', 'Infobollo')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(10) > div > div > a > h4', 'Stampa avviso di pagamento')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(11) > div > div > a > h4 > span', 'Hai bisogno di aiuto?')
      .assert.containsText('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(12) > div > div > a > h4', 'Area riservata')
      // memobollo
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(1) > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // pagamenti online pagina di servizio
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(2) > div > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // pago bollo
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(2) > div > div > div > ul > li:nth-child(1) > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // pago rate
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(2) > div > div > div > ul > li:nth-child(2) > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // scarica ricevuta pagamento
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(3) > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // calcola bollo
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(4) > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // fai osservazione su pagina - servizio
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(5) > div > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // osservazione avvisi scadenza
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(5) > div > div > ul > li:nth-child(1) > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // osservazione avvisi accertamento
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(5) > div > div > ul > li:nth-child(2) > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // consulta pratica
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(6) > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // chiedi la rateizzazione
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(7) > div > div > a')
      .waitForElementVisible('#btnIntVeicAvanti', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a > div:nth-child(2)')
      .waitForElementVisible('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(8) > div > div > a', 1000)
      // domanda discarico rimborso
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(8) > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // infobollo
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(9) > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // stampa avviso pagamento - pagina di servizio
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(10) > div > div > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // stampa avviso di scadenza
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(10) > div > div > ul > li:nth-child(1) > span > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#app', 1000)
      // stampa avviso di accertamento
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(10) > div > div > ul > li:nth-child(2) > span > a')
      .waitForElementVisible('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active', 1000)
      // click sul menu di navigazione e controllo elementi nel menu
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-memobollo > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-memobollo > a > span', 'Memobollo')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-pagobollo > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-pagobollo > a > span', 'Pagamenti Online')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-ricevutabollo > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-ricevutabollo > a > span', 'Scarica la ricevuta di un pagamento')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-calcolabollo > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-calcolabollo > a > span', 'Calcola il bollo')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-osservazioneavvisi > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-osservazioneavvisi > a > span', 'Osservazioni')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-verificapratica > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-verificapratica > a > span', 'Consulta una pratica')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-rateizzazione > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-rateizzazione > a > span', 'Chiedi la rateizzazione')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-discarico > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-discarico > a > span', 'Domanda discarico o rimborso')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-infobollo > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-infobollo > a > span', 'Infobollo')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-stampa-avviso > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-stampa-avviso > a > span', 'Stampa avviso di pagamento')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-aiuto > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-aiuto > a > span', 'Aiuto')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-area-riservata > a')
      .assert.containsText('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-area-riservata > a > span', 'Area riservata')
      // click su menu link
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-memobollo > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-memobollo > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-pagobollo > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-pagobollo > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-ricevutabollo > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-ricevutabollo > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-calcolabollo > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-calcolabollo > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-osservazioneavvisi > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-osservazioneavvisi > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-verificapratica > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-verificapratica > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-rateizzazione > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-verificapratica > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-discarico > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-discarico > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-infobollo > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-infobollo > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-stampa-avviso > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-stampa-avviso > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-aiuto > a')
      .click('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-aiuto > a')
      .waitForElementVisible('#app', 1000)
      .click('#sp-navbar > div > div > div.navbar-header > a.navbar-brand.router-link-active')
      .waitForElementVisible('#sp-drodpown-menu__BV_toggle_')
      .click('#sp-drodpown-menu__BV_toggle_')
      .waitForElementVisible('#sp-drodpown-menu > ul > li.bg-ico.bg-ico-area-riservata > a')
      .end()
  }
}
