module.exports = {
  'default e2e tests': function (browser) {
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/')
      .waitForElementVisible('#app', 500)
      .waitForElementVisible('#main-content', 500)
      .waitForElementVisible('#btnLogin', 500)
      .click('#btnLogin')
      .pause(1000)
      .waitForElementVisible('#userIsLogged', 500)
      .click("#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-tabs.areapersonale--tab.v-tabs--centered.theme--light > div > div.v-slide-group__wrapper > div > div:nth-child(3)")
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(1) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Memobollo')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(2) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Paga on line')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(3) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Scarica la ricevuta di un pagamento')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(4) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Calcola il bollo')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(5) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Fai un\'osservazione su')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(6) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Consulta una pratica')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(7) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Chiedi la rateizzazione di un avviso di accertamento')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(8) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Fai una domanda di discarico di cartella esattoriale o ingiunzione')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(9) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Infobollo')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(10) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Stampa avviso di pagamento')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(11) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Chiedi l\'esenzione per motivi di disabilità')
      .assert.containsText('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(12) > div > div > div.v-card__title.homeLinkBtn > a > span > h4', 'Chiedi la restituzione')
      .pause(1000)
      .click('#main-menu > div > button > span > i')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(2) > div.v-list-item__content.menuIcon.memobollo')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Memobollo')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(3) > div.v-list-item__content.menuIcon.pagamenti_online')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Paga on line')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(4) > div.v-list-item__content.menuIcon.scarica_ricevuta_pagamento')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Scarica la ricevuta di un pagamento')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(5) > div.v-list-item__content.menuIcon.calcola_bollo')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Calcola il bollo')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(6) > div.v-list-item__content.menuIcon.osservazioni')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Fai un\'osservazione')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(7) > div.v-list-item__content.menuIcon.consulta_pratica')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Consulta una pratica')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(8) > div.v-list-item__content.menuIcon.chiedi_rateizzazione')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Chiedi la rateizzazione di un avviso di accertamento')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(9) > div.v-list-item__content.menuIcon.domanda_discarico_rimborso')
      .pause(500)
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Fai una domanda di discarico di cartelle esattoriali e ingiunzioni')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(10) > div.v-list-item__content.menuIcon.infobollo')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Infobollo')
      .click('#main-menu > div > button')
      .pause(500)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(11) > div')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Stampa avviso di pagamento e piano di rateizzazione')
      .click('#main-menu > div > button')
      .pause(500)
      .waitForElementVisible('#userIsLogged', 500)
      .click('#userIsLogged')
      .click('#main-menu > div > button')
      .pause(1000)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(12) > div.v-list-item__content.menuIcon.domanda_esenzioni_disabilita_auth')
      .assert.containsText('#main-content > div > div:nth-child(1) > div:nth-child(1) > div > div > div > h1', 'Chiedi l\'esenzione per motivi di disabilità')
      .end()
  }
}
