module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/pratica/inserimento/rateizzazione')
      .waitForElementVisible('#app', 5000)
      .useXpath()
      .waitForElementVisible('//a[text()="Rappresentante legale"]', 5000)
      .click('//a[text()="Rappresentante legale"]')
      .useCss()
      .waitForElementVisible('#codiceFiscaleRL', 1000)
      .setValue('#codiceFiscaleRL', 'PRDCRL76D18L219G')
      .setValue('input[id=cognome]', 'van der Poel')
      .setValue('input[id=nome]', 'Mathieu')
      .setValue('input[id=dataDiNascita]', '20101990')
      .setValue('input[id=comune]', 'Ala di Stura')
      .setValue('input[id=provincia]', 'TO')
      .click('#sessoGroup > div > div:nth-child(2) > label')
      .click('#btnRappLegStep2')
      .waitForElementVisible('#btnRappLegCerca', 1000)
      .click('#btnRappLegCerca')
      .assert.containsText('#codFiscaleGroup > div > div', 'Il codice fiscale è obbligatorio.')
      .assert.containsText('#numeroProtocolloGroup > div > div', 'Il numero di protocollo è obbligatorio.')
      .setValue('input[id=codiceFiscaleRappresentanteLegale]', '00024770067')
      .setValue('input[id=numProt]', '00214010CJ477BY')
      .click('#btnRappLegCerca')
      .waitForElementVisible('#main-content', 5000)
      .waitForElementVisible('#codFiscale', 1000)
      .assert.containsText('#denominazione', 'ALBERGO RISTORANTE VITTORIA DI GRAMATICA ROBERTO & C. - S.N.C.')
      .assert.containsText('#codFiscale', 'CF: 00024770067')
      .assert.containsText('#denominazioneRL', 'MATHIEU VAN DER POEL')
      .assert.containsText('#codiceFiscaleRL', 'CF: PRDCRL76D18L219G')
      .assert.containsText('#sessoRL', 'SESSO: M')
      .assert.containsText('#dataDiNascitaRL', 'DATA DI NASCITA: 20/10/1990')
      .assert.containsText('#comuneDiNascitaRL', 'COMUNE DI NASCITA O STATO ESTERO: ALA DI STURA (TO)')
      .waitForElementVisible('#addProtocollo')
      .click('#addProtocollo')
      .waitForElementVisible('#numeroProtocollo')
      .setValue('#numeroProtocollo', '00214010CJ477BA')
      .click('#collapse-addItems > div > form > button')
      .waitForElementVisible('#elencoRate > div:nth-child(4) > div', 500)
      .waitForElementVisible('#deleteBtn_1', 500)
      .click('#deleteBtn_1')
      .waitForElementVisible('#closeDelete_1', 500)
      .waitForElementVisible('#removeFile_1', 500)
      .click('#removeFile_1')
      .waitForElementVisible('#main-content > div > div > div.app-container > div:nth-child(3) > div > div.action-button-wide > div > button', 1000)
      .click('#main-content > div > div > div.app-container > div:nth-child(3) > div > div.action-button-wide > div > button')
      .waitForElementVisible('#btnInvioRichiesta', 1000)
      .click('#btnInvioRichiesta')
      .assert.containsText('#informativa-privacy > div > div > div > div.error', 'Il consenso all\'informativa sulla privacy è obbligatorio.')
      .setValue('#email', 'daniel.scaletta@consulenti.csi.it')
      .setValue('#telefono', '3333333333')
      .click('#informativa-privacy > div > div > div > div.position-relative.d-inline-block > div')
      .click('#btnInvioRichiesta')
      .waitForElementVisible('#app', 1000)
      .assert.containsText('#esitoDomanda > p:nth-child(2) > strong', 'N° di protocollo 00000157/2020')
      .assert.containsText('#main-content > div > div > div.app-container > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(1)', 'Totale 737,42 €')
      .assert.containsText('#main-content > div > div > div.app-container > div > div:nth-child(2) > div:nth-child(2) > div > div:nth-child(2)', 'Numero rate 15')
      .assert.containsText('#denominazione', 'ALBERGO RISTORANTE VITTORIA DI GRAMATICA ROBERTO & C. - S.N.C.')
      .assert.containsText('#codFiscale', 'CF: 00024770067')
      .assert.containsText('#denominazioneRL', 'MATHIEU VAN DER POEL')
      .assert.containsText('#codiceFiscaleRL', 'CF: PRDCRL76D18L219G')
      .assert.containsText('#sessoRL', 'SESSO: M')
      .assert.containsText('#dataDiNascitaRL', 'DATA DI NASCITA: 20/10/1990')
      .assert.containsText('#comuneDiNascitaRL', 'COMUNE DI NASCITA O STATO ESTERO: ALA DI STURA (TO)')
      .assert.containsText('#main-content > div > div > div.app-container > div > div:nth-child(2) > div:nth-child(6) > p:nth-child(2)', 'daniel.scaletta@consulenti.csi.it')
      .assert.containsText('#main-content > div > div > div.app-container > div > div:nth-child(2) > div:nth-child(6) > p:nth-child(3)', '3333333333')
      .end()
  }
}
