module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/')
      .waitForElementVisible('#main-content', 500)
      .waitForElementVisible('#btnLogin', 500)
      .click('#btnLogin')
      .waitForElementVisible('#userIsLogged', 500)
      .click('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-tabs.areapersonale--tab.v-tabs--centered.theme--light > div > div.v-slide-group__wrapper > div > div:nth-child(3)')
      .click('#homePage-gridCard > div.tab-transparent.areaPersonale--page > div.row.justify-center > div > div.v-window.mt-12.px-4.pb-4.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(7) > div > div > div.v-card__title.homeLinkBtn > a > span > h4')
      .waitForElementVisible('#btnIntVeicAvanti', 1000)
      .click('#btnIntVeicAvanti')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div', 'Il codice fiscale è obbligatorio.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'Il numero di protocollo è obbligatorio.')
      .setValue('#codiceFiscaleIntestatarioVeicolo', 'nbbbbr69c68a182c') // jira STASP-520
      .setValue('#numeroProtocollo', '00615010cb871je')
      .click('#btnIntVeicAvanti')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 1000)
      .assert.containsText('#dati-anagrafici-intestatario > h2', 'Dati anagrafici del contribuente')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'BARBARA NEBBIA')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: NBBBBR69C68A182C')
      .assert.containsText('//*[@id="importoElencoRate"]/strong', '165,72 €')
      .assert.containsText('//*[@id="nProtElencoRate"]/strong', '00615010CB871JE')
      .click('//*[@id="formModRata"]/div[1]/div/div/div/div[1]/label') // click situazione disagiata
      .waitForElementVisible('//*[@id="numeroRate"]')
      .setValue('//*[@id="numeroRate"]', '40')
      .click('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div[3]/div/div[6]/div/button')
      .waitForElementVisible('//*[@id="formModRata"]/div[2]/div/div/div/div[2]/div/div/div[1]', 500)
      .assert.containsText('//*[@id="formModRata"]/div[2]/div/div/div/div[2]/div/div/div[1]', 'Il numero di rate deve essere inferiore o uguale al numero massimo di rate consentite (30)')
      .waitForElementVisible('//*[@id="formModRata"]/div[2]/div/div/div/div[1]/div[2]/div/button', 500)
      .click('//*[@id="formModRata"]/div[2]/div/div/div/div[1]/div[2]/div/button')
      .setValue('//*[@id="numeroRate"]', '1')
      .waitForElementVisible('//*[@id="formModRata"]/div[2]/div/div/div/div[2]/div/div/div', 500)
      .assert.containsText('//*[@id="formModRata"]/div[2]/div/div/div/div[2]/div/div/div', 'Il numero di rate deve essere superiore al numero di rate calcolato dalla procedura (5)')
      .waitForElementVisible('//*[@id="formModRata"]/div[2]/div/div/div/div[1]/div[2]/div/button', 500)
      .click('//*[@id="formModRata"]/div[2]/div/div/div/div[1]/div[2]/div/button')
      .setValue('//*[@id="numeroRate"]', '30')
      .click('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div[3]/div/div[6]/div/button')
      .waitForElementVisible('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div[3]/div/div[1]/div/div[1]/strong', 500)
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div[3]/div/div[1]/div/div[1]/strong', 'Totale: 165,72 €')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div[3]/div/div[1]/div/div[2]/div/strong', 'Numero rate: 30')
      .assert.containsText('//*[@id="denominazione"]', 'BARBARA NEBBIA')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: NBBBBR69C68A182C')
      .waitForElementVisible('//*[@id="btnInvioRichiesta"]', 1000)
      .click('//*[@id="btnInvioRichiesta"]')
      .assert.containsText('//*[@id="canaleEmail"]/div/div/div/div[2]/div/div/div', 'Devi specificare almeno uno fra e-mail e numero di telefono cellulare.')
      .assert.containsText('//*[@id="canaleSms"]/div/div/div/div[2]/div/div/div', 'Devi specificare almeno uno fra e-mail e numero di telefono cellulare.')
      .assert.containsText('//*[@id="informativa-privacy"]/div/div/div/div/div/div/div[2]/div/div', 'Il consenso all\'informativa sulla privacy è obbligatorio.')
      .setValue('//*[@id="email"]', 'carlo.peraudo@consulenti.csi.it')
      .setValue('//*[@id="telefono"]', '3332040510')
      .click('//*[@id="informativa-privacy"]/div/div/div/div/div/div/div[1]/label')
      .click('//*[@id="btnInvioRichiesta"]')
      .pause(500)
      // *[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[1]/div/div/div[1]/div/div[2]/div/p[1]/strong
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[1]/div/div/div[1]/div/div[2]/div/p[1]/strong', 'La domanda è stata registrata correttamente.')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[1]/div/div/div[1]/div/div[2]/div/p[2]/strong', 'N° di protocollo 00003723/2019')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[1]/div/div/div[1]/div/div[2]/div/p[3]', 'Conserva il numero di protocollo della pratica (controlla che sia arrivato via e-mail/SMS).')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[2]/div/div[1]', 'Totale 165,72 €')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[2]/div/div[2]', 'Numero rate 5')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[5]/p[1]', 'carlo.peraudo@consulenti.csi.it')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div/div[2]/div[5]/p[2]', '3332040510')
      .end()
  }
}
