// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage
// https://github.com/nightwatchjs/nightwatch-docs

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/pratica/verifica')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      .assert.containsText('#numeroGroup > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .clearValue('#codFiscPartIva')
      .setValue('input[id=numero]', '00002695/2019')
      .setValue('#codFiscPartIva', 'ZHOYHO65T17Z210Y')
      .click('button[type=submit]')
      .waitForElementVisible('#box-protocollo', 1000)
      .assert.containsText('#denominazione', 'YOUHAO ZHOU')
      .assert.containsText('#codFiscale', 'CF: ZHOYHO65T17Z210Y')
      .assert.containsText('#dati-veicolo > div > div:nth-child(1)', 'AUTOVEICOLO')
      .assert.containsText('#dati-veicolo > div > div:nth-child(2)', 'Targa: DC528AW')
      .waitForElementVisible('#modificaBtnRiferimenti', 1000)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 1000)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .waitForElementVisible('#backButton', 1000)
      .click('#backButton')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      .assert.containsText('#numeroGroup > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .clearValue('#codFiscPartIva')
      .setValue('input[id=numero]', '00000217/2019')
      .setValue('input[id=codFiscPartIva]', 'VRGLGU50B18H121A')
      .click('button[type=submit]')
      .waitForElementVisible('#main-content', 1000)
      .assert.containsText('#box-protocollo > div.h2', 'N° di protocollo 00000217/2019')
      .assert.containsText('#denominazione', 'LUIGI VERGANO')
      .assert.containsText('#codFiscale', 'CF: VRGLGU50B18H121A')
      .assert.containsText('#datiAnagrafici', 'NATO A: QUATTORDIO (AL) IL 18/02/1950')
      .assert.containsText('#sesso', 'SESSO: M')
      .assert.containsText('#titoloEsecutivo > h2', 'Titolo esecutivo: ingiunzione')
      .assert.containsText('#tipoTitolo', 'INGIUNZIONE: N° 11120008888888811000')
      .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 18/02/2019')
      .assert.containsText('#importoTotale', 'IMPORTO TOTALE RISCOSSIONE: 300,00 €')
      .assert.containsText('#oggettoDomanda', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('#motivoDomanda', 'PAGAMENTO ESEGUITO')
      .waitForElementVisible('#modificaBtnRiferimenti', 1000)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 1000)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .click('#backButton')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      .assert.containsText('#numeroGroup > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .clearValue('#codFiscPartIva')
      .setValue('input[id=numero]', '00003341/2019')
      .setValue('input[id=codFiscPartIva]', '00024770067')
      .click('button[type=submit]')
      .waitForElementVisible('#main-content', 1000)
      .assert.containsText('#numeroProtocollo', 'N° di protocollo 00003341/2019')
      .assert.containsText('#totaleImportoRate', 'Totale 737,42 €')
      .assert.containsText('#denominazione', 'ALBERGO RISTORANTE VITTORIA DI GRAMATICA ROBERTO & C. - S.N.C.')
      .assert.containsText('#codFiscale', 'CF: 00024770067')
      .waitForElementVisible('#modificaBtnRiferimenti', 1000)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 1000)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .click('#backButton')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      .assert.containsText('#numeroGroup > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#codFiscPartIvaGroup > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .clearValue('#codFiscPartIva')
      .setValue('input[id=numero]', '00001643/2019')
      .setValue('input[id=codFiscPartIva]', 'BAIMSM72B23B111H')
      .click('button[type=submit]')
      .waitForElementVisible('#numeroProtocollo', 2000)
      .assert.containsText('#numeroProtocollo', 'N° di protocollo 00001643/2019')
      .assert.containsText('#denominazione', 'MASSIMILIANO BAI')
      .assert.containsText('#codFiscale', 'CF: BAIMSM72B23B111H')
      .assert.containsText('#dati-veicolo > div > div:nth-child(1)', 'AUTOVEICOLO')
      .assert.containsText('#dati-veicolo > div > div:nth-child(2)', 'Targa: TO33955T')
      .assert.containsText('#dati-veicolo > div > div:nth-child(3)', 'Scadenza: 04/2017')
      .assert.containsText('#dati-veicolo > div > div:nth-child(4)', 'Validità: 12 mesi')
      .assert.containsText('#dati-veicolo > div > div:nth-child(5)', 'Importo: 246,13 €')
      .assert.containsText('#dati-avviso-scadenza > div > div', '201704000146086')
      .assert.containsText('#osservazioni-avv-scadenza > div > strong', 'Esenzione per altri motivi')
      .waitForElementVisible('#modificaBtnRiferimenti', 1000)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 1000)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .waitForElementVisible('#undoBtnMod', 1000)
      .click('#undoBtnMod')
      .end()
  }
}
