// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage
// https://github.com/nightwatchjs/nightwatch-docs

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/pratica/verifica')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=numero]', '00002695/2019') // MEMOR: Avviso di accertamento
      .setValue('#codFiscPartIva', 'ZHOYHO65T17Z210Y')
      .pause(200)
      .click('button[type=submit]')
      .waitForElementVisible('#box-protocollo', 1000)
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'YOUHAO ZHOU')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: ZHOYHO65T17Z210Y')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: DC528AW')
      .useCss()
      .waitForElementVisible('#modificaBtnRiferimenti', 200)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 1000)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .waitForElementVisible('#backButton', 1000)
      .click('#backButton')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=numero]', '00000217/2019')
      .setValue('input[id=codFiscPartIva]', 'VRGLGU50B18H121A')
      .click('button[type=submit]')
      .waitForElementVisible('#main-content', 1000)
      .assert.containsText('#box-protocollo > div.h2', 'N° di protocollo 00000217/2019')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'LUIGI VERGANO')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: VRGLGU50B18H121A')
      // .assert.containsText('#datiAnagrafici', 'NATO A: QUATTORDIO (AL) IL 18/02/1950')
      .assert.containsText('//*[@id="sesso"]', 'SESSO: M')
      .assert.containsText('//*[@id="titoloEsecutivo"]/h2', 'Titolo esecutivo: ingiunzione')
      .assert.containsText('//*[@id="tipoTitolo"]', 'INGIUNZIONE: N° 11120008888888811000')
      .assert.containsText('//*[@id="dataNotifica"]', 'DATA DI NOTIFICA: 18/02/2019')
      .assert.containsText('//*[@id="importoTotale"]', 'IMPORTO TOTALE RISCOSSIONE: 300,00 €')
      .assert.containsText('//*[@id="oggettoDomanda"]/div/div/div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('//*[@id="pagamentoEseguito"]', 'PAGAMENTO ESEGUITO')
      .useCss()
      .waitForElementVisible('#modificaBtnRiferimenti', 1000)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 200)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .click('#backButton')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      // .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=numero]', '00003341/2019')
      .setValue('input[id=codFiscPartIva]', '00024770067')
      .click('button[type=submit]')
      .waitForElementVisible('#box-protocollo', 1000)
      .assert.containsText('#numeroProtocollo', 'N° di protocollo 00003341/2019')
      .assert.containsText('#totaleImportoRate', 'Totale 737,42 €')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'ALBERGO RISTORANTE VITTORIA DI GRAMATICA ROBERTO & C. - S.N.C.')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: 00024770067')
      .useCss()
      .waitForElementVisible('#modificaBtnRiferimenti', 200)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 200)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .click('#backButton')
      .waitForElementVisible('#main-content', 500)
      .click('button[type=submit]')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div', 'Il numero di protocollo è obbligatorio.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA è obbligatorio.')
      .setValue('#codFiscPartIva', '0000 19')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-text-field__details > div > div > div', 'Il codice fiscale / P.IVA deve contenere solo lettere e numeri.')
      .setValue('input[id=numero]', '00001643/2019')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div.form-verifica-pratica.col-lg-4.col-md-6.offset-lg-1 > form > div.v-input.v-input--has-state.v-input--is-label-active.v-input--is-dirty.theme--light.v-text-field.v-text-field--is-booted.error--text > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=codFiscPartIva]', 'BAIMSM72B23B111H')
      .click('button[type=submit]')
      .waitForElementVisible('#numeroProtocollo', 1000)
      .assert.containsText('#numeroProtocollo', 'N° di protocollo 00001643/2019')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'MASSIMILIANO BAI')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: BAIMSM72B23B111H')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: TO33955T')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[3]', 'SCADENZA: 04/2017')
      // .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[4]', 'VALIDITÀ: 12 mesi')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[5]', 'IMPORTO: 246,13 €')
      .assert.containsText('//*[@id="dati-avviso-scadenza"]/div/div', '201704000146086')
      .useCss()
      .assert.containsText('#osservazioni-avv-scadenza > div > strong', 'Esenzione per altri motivi')
      .waitForElementVisible('#modificaBtnRiferimenti', 200)
      .click('#modificaBtnRiferimenti')
      .waitForElementVisible('#email', 200)
      .setValue('input[id=email]', 'email.email@email.it')
      .setValue('input[id=telefono]', '3333333333')
      .waitForElementVisible('#undoBtnMod', 1000)
      .click('#undoBtnMod')
      .end()
  }
}
