// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage
// https://github.com/nightwatchjs/nightwatch-docs

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/bollo/ricevuta')
      .waitForElementVisible('#main-content', 1000)
      .setValue('#iuv', 'RF02181970003T00200000002')
      .click('button[type=submit]')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 1000)
      .assert.containsText('#dati-anagrafici-intestatario > h2', 'Dati anagrafici intestatario pagamento')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'SABIA COLUCCI CARMINE ANGELO')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: SBCCMN35A30A519Z')
      .useCss()
      .assert.containsText('#dati-veicolo > h2', 'Dati del veicolo')
      .useXpath()
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: AT434CY')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[3]', 'SCADENZA: 12/2018')
      // .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[4]', 'VALIDITÀ: 12 mesi')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[5]', 'IMPORTO: 107,63 €')
      .useCss()
      .assert.containsText('#composizione-importo > h2', 'Composizione importo')
      .assert.containsText('#composizione-importo > table > tr:nth-child(1) > th', 'Tassa')
      .assert.containsText('#composizione-importo > table > tr:nth-child(1) > td', '103,60 €')
      .assert.containsText('#composizione-importo > table > tr:nth-child(2) > th', 'Sanzioni')
      .assert.containsText('#composizione-importo > table > tr:nth-child(2) > td', '3,89 €')
      .assert.containsText('#composizione-importo > table > tr:nth-child(3) > th', 'Interessi')
      .assert.containsText('#composizione-importo > table > tr:nth-child(3) > td', '0,14 €')
      .assert.containsText('#composizione-importo > table > tr:nth-child(4) > th > strong', 'Totale')
      .assert.containsText('#composizione-importo > table > tr:nth-child(4) > td > strong', '107,63 €')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(1) > td', 'Intesa Sanpaolo')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(2) > td', '201807160000002784977813')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(3) > td', 'TST000000000043957')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(4) > td', '15317425430420147011')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(5) > td', 'RF02181970003T00200000002')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(6) > td', '16/07/2018')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(7) > td', 'Pagamento effettuato')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(8) > td', 'Regione Piemonte')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(9) > td', '107,63 €')
      .click('#backButton')
      .waitForElementVisible('#main-content', 500)
      .setValue('#iuv', 'RF88193380003T00200000007')
      // .setValue('#iuv', 'RF88193380003T00200000001') // per caso farlocco
      .click('button[type=submit]')
      // .waitForElementVisible('#cercaPagamento > div > div > div.v-text-field__details > div > div > div', 2000)
      // .assert.containsText('#boxErrDiv > div > div > div.v-alert__content > div > div.col-md-10.col-12 > p', 'Codice di avviso di pagamento non trovato')
      // .assert.containsText('#boxErrDiv > div > div > div.v-alert__content > div > div.col-md-10.col-12 > h4', 'Attenzione, la ricerca non ha prodotto risultati.')
      // .assert.containsText('#cercaPagamento > div > div > div.v-text-field__details > div > div > div', 'Codice di avviso di pagamento non trovato')
      // .pause(500)
      // .click('#cercaPagamento > div > div > div.v-input__slot > div.v-input__append-inner > div > button')
      // document.querySelector("#cercaPagamento > div > div > div.v-input__slot > div.v-input__append-inner > div > button")
      //  .setValue('input[id=iuv]', 'RF88193380003T00200000007') // test ricevuta dopo pago rate
      // .setValue('#iuv', 'RF88193380003T00200000007')
      // .waitForElementVisible('#cercaPagamento > button > span',500)
      // .click('#cercaPagamento > button > span')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 1000)
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'GOLA PAOLO')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: GLOPLA75E21L219X')
      .useCss()
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(2) > div > dl.text-center.col-6.col-sm-3.offset-sm-2 > dd > strong', '50043679')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(2) > div > dl.text-center.col-6.col-sm-2 > dd > strong', '2019')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(2) > p:nth-child(3)', 'Totale importo rate pagate: 132,47 €')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(2) > p:nth-child(4)', 'Numero di rate pagate: 1')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(3) > div > div.noAccordion > div > div > div.col-md-5.col-sm-6.align-self-center.text-center > div > dl > dd', '01/11/2020')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(3) > div > div.noAccordion > div > div > div.col-md-4.col-sm-6.align-self-center > div > dl > dd', '4,51 €')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(1) > td', 'Intesa Sanpaolo')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(2) > td', 'TST000000000079071')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(3) > td', '15754748139270006011')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(4) > td', 'RF88193380003T00200000007')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(5) > td', '04/12/2019')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(6) > td', 'Pagamento effettuato')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(7) > td', 'Regione Piemonte')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.row.inner-cont-bollo > div > div.action-area > div > div:nth-child(4) > table > tr:nth-child(8) > td', '4,51 €')
      .click('#backButton')
      .waitForElementVisible('#main-content', 1000)
      .end()
  }
}
