// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage
// https://github.com/nightwatchjs/nightwatch-docs

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/')
      .waitForElementVisible('#main-content', 1000)
      .click('#homePage-gridCard > div > div:nth-child(10) > div > div.v-card__title.homeLinkBtn > a > span > h4') // click card Stampa avviso di pagamento
      .click('#main-content > div > div:nth-child(1) > div.container > div > div > div > div.form-cerca-veicolo.form-scelta-tipo.col-lg-4.col-md-6.offset-lg-1 > div.space-section > a')
      .waitForElementVisible('#iuv', 1000)
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > strong', 'Cerca un avviso di scadenza da stampare')
      .click('button[type=submit]')
      // .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div > div > div.v-text-field__details > div > div > div', 'Lo IUV / Codice di avviso di pagamento è obbligatorio.')
      .setValue('input[id=iuv]', '10 51')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div > div > div.v-text-field__details > div > div > div', 'Lo IUV / Codice di avviso di pagamento deve contenere solo lettere e numeri.')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=iuv]', '20191115001')
      .click('button[type=submit]')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 500)
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'EGAN BERNAL')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: BRNGNE50S68C983X')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: EH252RL')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[1]/strong', '10/2017')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[2]/strong', '12 MESI')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[3]/strong', '150,15 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[4]/strong', '9,01 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[5]/strong', '1,89 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[6]/strong', 'TOTALE: 161,05 €')
      .useCss()
      .click('#backButton')
      .waitForElementVisible('#iuv', 1000)
      .useXpath()
      .click('//*[@id="main-content"]/div/div[1]/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[3]')
      .useCss()
      .waitForElementVisible('#cercaPagamVeicoloBtn', 500)
      .click('button[id=cercaPagamVeicoloBtn]')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div', 'Il codice fiscale è obbligatorio.')
      .setValue('input[id=codiceFiscale]', '10 51')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div:nth-child(1)', 'Il codice fiscale deve avere una lunghezza minima di 11 caratteri.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div:nth-child(2)', 'Il codice fiscale deve contenere solo lettere e numeri.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'La targa è obbligatoria.')
      .setValue('input[id=targa]', 'AK 9')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'La targa deve contenere solo lettere e numeri.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(3) > div > div.v-text-field__details > div > div > div', 'Specificare il tipo di veicolo.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(4) > div > div.v-text-field__details > div > div > div', 'Specificare il mese di scadenza.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(5) > div > div.v-text-field__details > div > div > div', 'Specificare l\'anno di scadenza.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(6) > div > div.v-text-field__details > div > div > div', 'Specificare i mesi di validità.')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=codiceFiscale]', 'REXGLI17D05C722K')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(2) > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=targa]', 'AK899UO')
      .setValue('input[id="tipoVeicolo"]', 'A')
      .setValue('#meseScadenza', 12) // attenzione: per far funzionare i test, le API su json-server sulla scadenza mese restituiscono - ad esempio - "1" - "1" (stesso valore per value-text), e non "GENNAIO" - "1"
      .setValue('input[id="annoScadenza"]', 2019)
      .setValue('#Validitamesi', '12')
      .moveToElement('#cercaPagamVeicoloBtn', 2, 2)
      .saveScreenshot('test/e2e/reports/form_stampa_bollett.jpg')
      .click('#cercaPagamVeicoloBtn')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'EGAN BERNAL')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: BRNGNE50S68C983X')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: EH252RL')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[1]/strong', '10/2017')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[2]/strong', '12 MESI')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[3]/strong', '150,15 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[4]/strong', '9,01 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[5]/strong', '1,89 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[6]/strong', 'TOTALE: 161,05 €')
      .useCss()
      .click('#main-menu > div > button > span > i')
      .pause(100)
      .click('#main-menu-list > div.v-navigation-drawer__content > div > div.v-list.main-menu-left-offcanvas.v-sheet.theme--light.v-list--dense.v-list--nav > div > div:nth-child(11) > div')
      .waitForElementVisible('#main-content > div > div:nth-child(1) > div.container > div > div > div > div.form-cerca-veicolo.form-scelta-tipo.col-lg-4.col-md-6.offset-lg-1 > div:nth-child(2) > a > span', 1000)
      .click('#main-content > div > div:nth-child(1) > div.container > div > div > div > div.form-cerca-veicolo.form-scelta-tipo.col-lg-4.col-md-6.offset-lg-1 > div:nth-child(2) > a > span') // accertamento
      .waitForElementVisible('#iuv', 500)
      .click('button[type=submit]')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div > div > div.v-text-field__details > div > div > div', 'Lo IUV / Codice di avviso di pagamento è obbligatorio.')
      .setValue('input[id=iuv]', '10 51')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div > div > div.v-text-field__details > div > div > div', 'Lo IUV / Codice di avviso di pagamento deve contenere solo lettere e numeri.')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=iuv]', '192630498508831')
      .click('button[type=submit]')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'VALERYK BRESCIANI')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: BRSVRY92T62F902F')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: FC704AG')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[1]/strong', '10/2017')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[2]/strong', '12 MESI')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[3]/strong', '150,15 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[4]/strong', '9,01 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[5]/strong', '1,89 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[6]/strong', 'TOTALE: 161,05 €')
      .useCss()
      .click('#backButton')
      .waitForElementVisible('#iuv', 500)
      .useXpath()
      .click('//*[@id="main-content"]/div/div[1]/div[2]/div[2]/div/div[2]/div/div[2]/div/div[2]/div/div[3]')
      .useCss()
      .waitForElementVisible('#cercaPagamVeicoloBtn', 500)
      .click('button[id=cercaPagamVeicoloBtn]')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div', 'Il codice fiscale è obbligatorio.')
      .setValue('input[id=codiceFiscale]', '10 51')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div:nth-child(1)', 'Il codice fiscale deve avere una lunghezza minima di 11 caratteri.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-text-field__details > div > div > div:nth-child(2)', 'Il codice fiscale deve contenere solo lettere e numeri.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'La targa è obbligatoria.')
      .setValue('input[id=targa]', 'AK 9')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(2) > div > div.v-text-field__details > div > div > div', 'La targa deve contenere solo lettere e numeri.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(3) > div > div.v-text-field__details > div > div > div', 'Specificare il tipo di veicolo.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(4) > div > div.v-text-field__details > div > div > div', 'Specificare il mese di scadenza.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(5) > div > div.v-text-field__details > div > div > div', 'Specificare l\'anno di scadenza.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(6) > div > div.v-text-field__details > div > div > div', 'Specificare i mesi di validità.')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(1) > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=codiceFiscale]', 'BRSVRY92T62F902F')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > form > div:nth-child(2) > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=targa]', 'FC704AG')
      .setValue('input[id="tipoVeicolo"]', 'A')
      .setValue('#meseScadenza', 10) // attenzione: per far funzionare i test, le API su json-server sulla scadenza mese restituiscono - ad esempio - "1" - "1" (stesso valore per value-text), e non "GENNAIO" - "1"
      .setValue('input[id="annoScadenza"]', 2017)
      .setValue('#Validitamesi', '12')
      .click('#cercaPagamVeicoloBtn')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'VALERYK BRESCIANI')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: BRSVRY92T62F902F')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: FC704AG')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[1]/strong', '10/2017')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[2]/strong', '12 MESI')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[3]/strong', '150,15 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[4]/strong', '9,01 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[5]/strong', '1,89 €')
      .assert.containsText('//*[@id="dati-avviso-di-pagamento"]/div/div/div[6]/strong', 'TOTALE: 161,05 €')
      .end()
  }
}
