// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage
// https://github.com/nightwatchjs/nightwatch-docs

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL
    
    browser
      .url(devServer + '/')
      .waitForElementVisible('#main-content', 1000)
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(10) > div > div > a')
      .waitForElementVisible('#main-content > div > div > div.app-container > div.app-row.inner-cont-bollo > div.form-cerca-veicolo.col-xxl-4.col-md-6.offset-xxl-1 > div.space-section > h2', 1000)
      .assert.containsText('#main-content > div > div > div.app-container > div.app-row.inner-cont-bollo > div.form-cerca-veicolo.col-xxl-4.col-md-6.offset-xxl-1 > div.space-section > h2', 'Avviso di scadenza')
      .click('#main-content > div > div > div.app-container > div.app-row.inner-cont-bollo > div.form-cerca-veicolo.col-xxl-4.col-md-6.offset-xxl-1 > div.space-section > a')
      .waitForElementVisible('#iuv', 1000)
      .assert.containsText('#main-content > div > div > div.service-title > div > div > h1', 'Stampa avviso di pagamento - scadenza')
      .click('button[type=submit]')
      .assert.containsText('#iuvGroup > div > div', 'Lo IUV / Codice di avviso di pagamento è obbligatorio.')
      .setValue('input[id=iuv]', '10 51')
      .assert.containsText('#iuvGroup > div > div', 'Lo IUV / Codice di avviso di pagamento deve contenere solo lettere e numeri.')
      .clearValue('input[id=iuv]')
      .setValue('input[id=iuv]', '20191115001')
      .click('button[type=submit]')
      .waitForElementVisible('#main-content > div > div > div.app-container > div.app-row.inner-cont-bollo > div > div.action-area > div > div:nth-child(1) > h2', 1000)
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(1)', 'EGAN BERNAL')
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(2)', 'CF: BRNGNE50S68C983X')
      .assert.containsText('#dati-veicolo > div > div:nth-child(1)', 'AUTOVEICOLO')
      .assert.containsText('#dati-veicolo > div > div:nth-child(2)', 'Targa: EH252RL')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(1)', 'SCADENZA: 10/2017')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(2)', 'VALIDITÀ: 12 MESI')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(3)', 'COSTO DEL BOLLO: 150,15 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(4)', 'SANZIONE: 9,01 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(5)', 'INTERESSI: 1,89 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(6)', 'TOTALE: 161,05 €')
      .click('#main-content > div > div > div.app-container > div.app-row.inner-cont-bollo > div > div.action-button-wide > div:nth-child(1) > a')
      .waitForElementVisible('#iuv', 1000)
      .useXpath()
      .click('//a[text()="Dati del veicolo"]')
      .useCss()
      .waitForElementVisible('#codiceFiscaleGroup', 1000)
      .click('button[id=cercaPagamVeicoloBtn]')
      .assert.containsText('#codiceFiscaleGroup > div > div', 'Il Codice fiscale è obbligatorio.')
      .setValue('input[id=codiceFiscale]', '10 51')
      .assert.containsText('#codiceFiscaleGroup > div > div', 'Il Codice fiscale deve contenere solo lettere e numeri.')
      .assert.containsText('#targaGroup > div > div', 'La targa è obbligatoria/o.')
      .setValue('input[id=targa]', 'AK 9')
      .assert.containsText('#targaGroup > div > div', 'La targa deve contenere solo lettere e numeri.')
      .assert.containsText('#tipoVeicoloGroup > div > div', 'Specificare il tipo di veicolo.')
      .assert.containsText('#meseScadenzaGroup > div > div', 'Specificare il mese di scadenza.')
      .assert.containsText('#annoScadenzaGroup > div > div', 'Specificare l\'anno di scadenza.')
      .assert.containsText('#mesiValiditaGroup > div > div', 'Specificare i mesi di validità.')
      .clearValue('input[id=codiceFiscale]')
      .setValue('input[id=codiceFiscale]', 'REXGLI17D05C722K')
      .clearValue('input[id=targa]')
      .setValue('input[id=targa]', 'AK899UO')
      .setValue('select[id="tipoVeicolo"]', 'A')
      .click('select[id="meseScadenza"] option[value="12"]')
      .setValue('select[id="annoScadenza"]', 2019)
      .setValue('select[id="mesiValidita"]', 12)
      .click('#cercaPagamVeicoloBtn')
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(1)', 'EGAN BERNAL')
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(2)', 'CF: BRNGNE50S68C983X')
      .assert.containsText('#dati-veicolo > div > div:nth-child(1)', 'AUTOVEICOLO')
      .assert.containsText('#dati-veicolo > div > div:nth-child(2)', 'Targa: EH252RL')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(1)', 'SCADENZA: 10/2017')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(2)', 'VALIDITÀ: 12 MESI')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(3)', 'COSTO DEL BOLLO: 150,15 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(4)', 'SANZIONE: 9,01 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(5)', 'INTERESSI: 1,89 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(6)', 'TOTALE: 161,05 €')
      .click('#sp-navbar > div > div > div.navbar-header > a')
      .waitForElementVisible('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(10) > div > div > ul > li:nth-child(2) > span > a', 1000)
      .click('#main-content > div > div > div.container.page.full-card-grid > div > div > div > div:nth-child(10) > div > div > ul > li:nth-child(2) > span > a') // accertamento
      .waitForElementVisible('#iuv', 500)
      .click('button[type=submit]')
      .assert.containsText('#iuvGroup > div > div', 'Lo IUV / Codice di avviso di pagamento è obbligatorio.')
      .setValue('input[id=iuv]', '10 51')
      .assert.containsText('#iuvGroup > div > div', 'Lo IUV / Codice di avviso di pagamento deve contenere solo lettere e numeri.')
      .clearValue('input[id=iuv]')
      .setValue('input[id=iuv]', '192630498508831')
      .click('button[type=submit]')
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(1)', 'VALERYK BRESCIANI')
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(2)', 'CF: BRSVRY92T62F902F')
      .assert.containsText('#dati-veicolo > div > div:nth-child(1)', 'AUTOVEICOLO')
      .assert.containsText('#dati-veicolo > div > div:nth-child(2)', 'Targa: FC704AG')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(1)', 'SCADENZA: 10/2017')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(2)', 'VALIDITÀ: 12 MESI')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(3)', 'COSTO DEL BOLLO: 150,15 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(4)', 'SANZIONE: 9,01 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(5)', 'INTERESSI: 1,89 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(6) > strong', 'TOTALE: 161,05 €')
      .click('#action-buttons > div:nth-child(1) > a:nth-child(1)')
      .waitForElementVisible('#iuv', 1000)
      .useXpath()
      .click('//a[text()="Dati del veicolo"]')
      .useCss()
      .waitForElementVisible('#codiceFiscaleGroup', 1000)
      .click('button[id=cercaPagamVeicoloBtn]')
      .assert.containsText('#codiceFiscaleGroup > div > div', 'Il Codice fiscale è obbligatorio.')
      .setValue('input[id=codiceFiscale]', '10 51')
      .assert.containsText('#codiceFiscaleGroup > div > div', 'Il Codice fiscale deve contenere solo lettere e numeri.')
      .assert.containsText('#targaGroup > div > div', 'La targa è obbligatoria/o.')
      .setValue('input[id=targa]', 'AK 9')
      .assert.containsText('#targaGroup > div > div', 'La targa deve contenere solo lettere e numeri.')
      .assert.containsText('#tipoVeicoloGroup > div > div', 'Specificare il tipo di veicolo.')
      .assert.containsText('#meseScadenzaGroup > div > div', 'Specificare il mese di scadenza.')
      .assert.containsText('#annoScadenzaGroup > div > div', 'Specificare l\'anno di scadenza.')
      .assert.containsText('#mesiValiditaGroup > div > div', 'Specificare i mesi di validità.')
      .clearValue('input[id=codiceFiscale]')
      .setValue('input[id=codiceFiscale]', 'BRSVRY92T62F902F')
      .clearValue('input[id=targa]')
      .setValue('input[id=targa]', 'FC704AG')
      .setValue('select[id="tipoVeicolo"]', 'A')
      .click('select[id="meseScadenza"] option[value="10"]')
      .setValue('select[id="annoScadenza"]', 2017)
      .setValue('select[id="mesiValidita"]', 12)
      .click('#cercaPagamVeicoloBtn')
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(1)', 'VALERYK BRESCIANI')
      .assert.containsText('#dati-anagrafici-intestatario > div > div:nth-child(2)', 'CF: BRSVRY92T62F902F')
      .assert.containsText('#dati-veicolo > div > div:nth-child(1)', 'AUTOVEICOLO')
      .assert.containsText('#dati-veicolo > div > div:nth-child(2)', 'Targa: FC704AG')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(1)', 'SCADENZA: 10/2017')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(2)', 'VALIDITÀ: 12 MESI')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(3)', 'COSTO DEL BOLLO: 150,15 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(4)', 'SANZIONE: 9,01 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(5)', 'INTERESSI: 1,89 €')
      .assert.containsText('#dati-avviso-di-pagamento > div > div:nth-child(6) > strong', 'TOTALE: 161,05 €')
      .end()
  }
}
