module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/pratica/inserimento/domanda_discarico_rimborso/')
      .waitForElementVisible('#main-content', 500)
      .waitForElementVisible('#btnIntVeicAvanti', 500)
      .click('#btnIntVeicAvanti')
      .assert.containsText('#codFiscaleGroup > div > div', 'Il codice fiscale è obbligatorio.')
      .setValue('#codiceFiscaleIntestatarioIngiunzione', 'MMMNTN68A16C632X')
      .click('#btnIntVeicAvanti')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 1000)
      .assert.containsText('#dati-anagrafici-intestatario > h2', 'Dati anagrafici intestatario ingiunzione / cartella')
      .assert.containsText('#denominazione', 'ANTONIO MAMMARELLA GIARDINIERI')
      .assert.containsText('#codFiscale', 'CF: MMMNTN68A16C632X')
      .assert.containsText('#datiAnagrafici', 'NATO A: CHIETI (CH) IL 16/01/1968')
      .assert.containsText('#sesso', 'SESSO: M')
      .useXpath()
      .waitForElementVisible('//a[text()="Cartella"]', 1000)
      .click('//a[text()="Cartella"]')
      .useCss()
      .waitForElementVisible('#numeroCartellaEsattoriale', 1000)
      .setValue('#numeroCartellaEsattoriale', '0000000000000000')
      .setValue('#dataNotificaIng', '20121900')
      .setValue('#totaleRiscossione', '123.10')
      .click('#discaricoAmministrativo')
      .click('#discaricoAmministrativo-totale')
      .click('#mancanzaPresupposto')
      .waitForElementVisible('#stepAvanti', 5000)
      .click('#stepAvanti')
      .waitForElementVisible('#app', 1000)
      .waitForElementVisible('#tipoTitolo', 1000)
      .assert.containsText('#tipoTitolo', 'CARTELLA: N° 000000000000')
      .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 20/12/1900')
      .assert.containsText('#importoTotale', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      .assert.containsText('#oggettoDomanda > div > div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('#motivoDomanda > div > div', 'MANCANZA DEL PRESUPPOSTO')
      .waitForElementVisible('#email', 1000)
      .setValue('#email', 'daniel.scaletta@consulenti.csi.it')
      .click('#informativa-privacy > div > div > div > div > div > label')
      .click('#inviaRichiestaDTE')
      .waitForElementVisible('#app', 1000)
      .waitForElementVisible('#denominazione', 1000)
      .assert.containsText('#esitoDomanda > p:nth-child(2) > strong', 'N° di protocollo 00000139/2020')
      .assert.containsText('#denominazione', 'ANTONIO MAMMARELLA GIARDINIERI')
      .assert.containsText('#codFiscale', 'CF: MMMNTN68A16C632X')
      .assert.containsText('#datiAnagrafici', 'NATO A: CHIETI (CH) IL 16/01/1968')
      .assert.containsText('#sesso', 'SESSO: M')
      .assert.containsText('#titoloEsecutivo', 'Titolo esecutivo: ingiunzione')
      .assert.containsText('#tipoTitolo', 'INGIUNZIONE: N° S116000210420')
      .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 08/01/2020')
      .assert.containsText('#importoTotale', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      .assert.containsText('#oggettoDomanda > div > div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('#motivoDomanda > div > div', 'PAGAMENTO ESEGUITO')
      .waitForElementVisible('#main-content > div > div > div.app-container > div:nth-child(2) > div > div.action-button-wide > div:nth-child(1) > button', 1000)
      .waitForElementVisible('#main-content > div > div > div.app-container > div:nth-child(2) > div > div.action-button-wide > div:nth-child(1) > button', 1000)
      // TODO DA QUI
      .end()
  }
}
