module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/pratica/inserimento/domanda_discarico/')
      .waitForElementVisible('#main-content', 500)
      .useXpath()
      .waitForElementVisible('//*[@id="main-content"]/div/div[1]/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div[3]', 1000)
      .click('//*[@id="main-content"]/div/div[1]/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div[3]')
      .useCss()
      .waitForElementVisible('#codiceFiscaleRL', 1000)
      .setValue('#codiceFiscaleRL', 'PRDCRL76D18L219G')
      .setValue('input[id=cognome]', 'van der Poel')
      .setValue('input[id=nome]', 'Mathieu')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > div:nth-child(1) > div.space-section > form > div.v-input.theme--light.v-input--selection-controls.v-input--radio-group.v-input--radio-group--row > div > div.v-input__slot > div > div:nth-child(3) > label')
      .setValue('input[id=dataDiNascita]', '01/10/1999')//input date cambiato per accessibilità
      .click('input[id=comune]')
      .setValue('input[id=comune]', 'Ala di Stura')
      .setValue('input[id=provincia]', 'TO')
      .saveScreenshot('test/e2e/reports/rappr_legale.jpg')
      .click('#rappLegaleAvanti')
      .pause(1000)
      .saveScreenshot('test/e2e/reports/cod_fiscale_rappr.jpg')
      .setValue('#codiceFiscaleIntestatarioIngiunzioneRL', '00368570859')
      .click('#cercaDTERL')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 1000)
      .assert.containsText('#dati-anagrafici-intestatario > h2', 'Dati anagrafici intestatario ingiunzione / cartella')
      // .useXpath()
      // .assert.containsText('//*[@id="denominazione"]', 'SCAM S.R.L.')
      // .assert.containsText('//*[@id="codFiscale"]', 'CF: 00368570859')
      // .assert.containsText('//*[@id="denominazione"]', 'MATHIEU VAN DER POEL')
      // .assert.containsText('//*[@id="codiceFiscaleRL"]', 'CF: PRDCRL76D18L219G')
      // .assert.containsText('//*[@id="sessoRL"]', 'SESSO: M')
      // .assert.containsText('//*[@id="comuneDiNascitaRL"]', 'COMUNE DI NASCITA O STATO ESTERO: ALA DI STURA (TO)')
      // .click('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div[3]/div[3]/div/form/div[1]/div[1]/div/div[2]/div/div[3]')
      // .useCss()
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div:nth-child(3) > div:nth-child(4) > div > form > div.tab-content-notHp > div.v-tabs.tabServizi.v-tabs--centered.v-tabs--fixed-tabs.theme--light > div > div.v-slide-group__wrapper > div > div.v-tab.v-tab--active')
      .setValue('input[id="numIngiunzione"]', 'S116000391505')
      .setValue('#totaleRiscossione', '123.10')
      .click('#discaricoAmministrativo')
      .pause(200)
      .click('#discaricoAmministrativo-totale')
      .pause(200)
      .click('#mancanzaPresupposto')
      .pause(200)
      .click('#stepAvanti')
      .waitForElementVisible('#titoloEsecutivo > h2', 1000)
      .assert.containsText('#titoloEsecutivo > h2', 'Titolo esecutivo: ingiunzione')
      // .useXpath()
      // .assert.containsText('//*[@id="tipoTitolo"]', 'INGIUNZIONE: N° S116000391505')
      // // .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 20/12/1900')
      // .assert.containsText('//*[@id="importoTotale"]', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      // .assert.containsText('//*[@id="oggettoDomanda"]/div/div/div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      // .assert.containsText('//*[@id="pagamentoEseguito"]', 'MANCANZA DEL PRESUPPOSTO')
      .waitForElementVisible('#email', 1000)
      .setValue('#email', 'daniel.scaletta@consulenti.csi.it')
      .click('#informativa-privacy > div > div > div > div > div > div > div.v-input__slot > label')
      .click('#inviaRichiestaDTE')
      .waitForElementVisible('#app', 1000)
      .waitForElementVisible('#denominazione', 1000)
      // .assert.containsText('#esitoDomanda > p:nth-child(2) > strong', 'N° di protocollo 00000149/2020')
      // .assert.containsText('#denominazione', 'SCAM S.R.L.')
      // .assert.containsText('#codFiscale', 'CF: 00368570859')
      // .assert.containsText('#denominazioneRL', 'MATHIEU VAN DER POEL')
      // .assert.containsText('#codiceFiscaleRL', 'CF: PRDCRL76D18L219G')
      // .assert.containsText('#sessoRL', 'SESSO: M')
      // .assert.containsText('#dataDiNascitaRL', 'DATA DI NASCITA: 20/10/1990')
      // .assert.containsText('#comuneDiNascitaRL', 'COMUNE DI NASCITA O STATO ESTERO: ALA DI STURA (TO)')
      // .assert.containsText('#titoloEsecutivo', 'Titolo esecutivo: ingiunzione')
      // .assert.containsText('#tipoTitolo', 'INGIUNZIONE: N° S116000210420')
      // .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 08/01/2020')
      // .assert.containsText('#importoTotale', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      // .assert.containsText('#oggettoDomanda > div > div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      // .assert.containsText('#motivoDomanda > div > div', 'PAGAMENTO ESEGUITO')
      .end()
  }
}
