module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/pratica/inserimento/domanda_discarico_rimborso/')
      .waitForElementVisible('#main-content', 500)
      .useXpath()
      .waitForElementVisible('//a[text()="Rappresentante legale"]', 5000)
      .click('//a[text()="Rappresentante legale"]')
      .useCss()
      .waitForElementVisible('#codiceFiscaleRL', 1000)
      .setValue('#codiceFiscaleRL', 'PRDCRL76D18L219G')
      .setValue('input[id=cognome]', 'van der Poel')
      .setValue('input[id=nome]', 'Mathieu')
      .setValue('input[id=dataDiNascita]', '20101990')
      .setValue('input[id=comune]', 'Ala di Stura')
      .setValue('input[id=provincia]', 'TO')
      .click('#sessoGroup > div > div:nth-child(2) > label')
      .click('#rappLegaleAvanti')
      .waitForElementVisible('#cercaDTERL', 1000)
      .click('#cercaDTERL')
      .assert.containsText('#codFiscaleGroup > div > div', 'Il codice fiscale è obbligatorio.')
      .setValue('#codiceFiscaleIntestatarioIngiunzioneRL', '00368570859')
      .click('#cercaDTERL')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 1000)
      .assert.containsText('#dati-anagrafici-intestatario > h2', 'Dati anagrafici intestatario ingiunzione / cartella')
      .assert.containsText('#denominazione', 'SCAM S.R.L.')
      .assert.containsText('#codFiscale', 'CF: 00368570859')
      .assert.containsText('#denominazioneRL', 'MATHIEU VAN DER POEL')
      .assert.containsText('#codiceFiscaleRL', 'CF: PRDCRL76D18L219G')
      .assert.containsText('#sessoRL', 'SESSO: M')
      .assert.containsText('#dataDiNascitaRL', 'DATA DI NASCITA: 20/10/1990')
      .assert.containsText('#comuneDiNascitaRL', 'COMUNE DI NASCITA O STATO ESTERO: ALA DI STURA (TO)')
      .assert.containsText('#datiIndirizzoIntestatario','VIA C COLOMBO 146 | GELA (CL) | 93012')
      .useXpath()
      .waitForElementVisible('//a[text()="Cartella"]', 1000)
      .click('//a[text()="Cartella"]')
      .useCss()
      .waitForElementVisible('#numeroCartellaEsattoriale', 1000)
      .setValue('#numeroCartellaEsattoriale', '0000000000000000')
      .useXpath()
      .waitForElementVisible('//a[text()="Ingiunzione"]', 1000)
      .click('//a[text()="Ingiunzione"]')
      .useCss()
      .setValue('select[id="numIngiunzione"]', 'S116000391505')
      .setValue('#dataNotificaIng', '20121900')
      .setValue('#totaleRiscossione', '123.10')
      .click('#discaricoAmministrativo')
      .click('#discaricoAmministrativo-totale')
      .click('#mancanzaPresupposto')
      .waitForElementVisible('#stepAvanti', 5000)
      .click('#stepAvanti')
      .waitForElementVisible('#app', 1000)
      .waitForElementVisible('#tipoTitolo', 1000)
      .assert.containsText('#tipoTitolo', 'INGIUNZIONE: N° S116000391505')
      .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 20/12/1900')
      .assert.containsText('#importoTotale', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      .assert.containsText('#oggettoDomanda > div > div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('#motivoDomanda > div > div', 'MANCANZA DEL PRESUPPOSTO')
      .waitForElementVisible('#backButton')
      .click('#backButton')
      .waitForElementVisible('#rimborsoPagamento', 500)
      .click('#rimborsoPagamento')
      .setValue('#rimborsoPagamento-iban', 'GB33BUKB20201555555555')
      .waitForElementVisible('#stepAvanti', 1000)
      .click('#stepAvanti')
      .waitForElementVisible('#oggettoDomanda', 1000)
      .assert.containsText('#oggettoDomanda > div > div', 'CHIEDO IL RIMBORSO, AVENDO GIÀ PROVVEDUTO AL PAGAMENTO')
      .assert.containsText('#oggettoDomanda > div > div > p', 'IBAN: GB33BUKB20201555555555')
      .waitForElementVisible('#email', 1000)
      .setValue('#email', 'daniel.scaletta@consulenti.csi.it')
      .click('#informativa-privacy > div > div > div > div > div > label')
      .click('#inviaRichiestaDTE')
      .waitForElementVisible('#app', 1000)
      .waitForElementVisible('#denominazione', 1000)
      .assert.containsText('#esitoDomanda > p:nth-child(2) > strong', 'N° di protocollo 00000149/2020')
      .assert.containsText('#denominazione', 'SCAM S.R.L.')
      .assert.containsText('#codFiscale', 'CF: 00368570859')
      .assert.containsText('#denominazioneRL', 'MATHIEU VAN DER POEL')
      .assert.containsText('#codiceFiscaleRL', 'CF: PRDCRL76D18L219G')
      .assert.containsText('#sessoRL', 'SESSO: M')
      .assert.containsText('#dataDiNascitaRL', 'DATA DI NASCITA: 20/10/1990')
      .assert.containsText('#comuneDiNascitaRL', 'COMUNE DI NASCITA O STATO ESTERO: ALA DI STURA (TO)')
      .assert.containsText('#titoloEsecutivo', 'Titolo esecutivo: ingiunzione')
      .assert.containsText('#tipoTitolo', 'INGIUNZIONE: N° S116000210420')
      .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 08/01/2020')
      .assert.containsText('#importoTotale', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      .assert.containsText('#oggettoDomanda > div > div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('#motivoDomanda > div > div', 'PAGAMENTO ESEGUITO')
      .waitForElementVisible('#main-content > div > div > div.app-container > div:nth-child(2) > div > div.action-button-wide > div:nth-child(1) > button', 1000)
      .waitForElementVisible('#main-content > div > div > div.app-container > div:nth-child(2) > div > div.action-button-wide > div:nth-child(1) > button', 1000)
      .end()
  }
}
