module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/pratica/inserimento/domanda_discarico/')
      .waitForElementVisible('#main-content', 500)
      .waitForElementVisible('#btnIntVeicAvanti', 500)
      .click('#btnIntVeicAvanti')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div > div > form > div > div > div.v-text-field__details > div > div > div', 'Il codice fiscale è obbligatorio.')
      .setValue('#codiceFiscaleIntestatarioIngiunzione', 'MMMNTN68A16C632X')
      .click('#btnIntVeicAvanti')
      .waitForElementVisible('#dati-anagrafici-intestatario > h2', 1000)
      .assert.containsText('#dati-anagrafici-intestatario > h2', 'Dati anagrafici intestatario ingiunzione / cartella')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'ANTONIO MAMMARELLA GIARDINIERI')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: MMMNTN68A16C632X')
      .assert.containsText('//*[@id="sesso"]', 'SESSO: M')
      .useCss()
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div:nth-child(3) > div:nth-child(3) > div > h2', 'Titolo esecutivo: Ingiunzione / Cartella')
      .useXpath()
      .click('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div[3]/div[3]/div/form/div[1]/div[1]/div/div[2]/div/div[3]')
      .useCss()
      .waitForElementVisible('#numeroCartellaEsattoriale', 500)
      .saveScreenshot('test/e2e/reports/cartella_esatt.jpg')
      .setValue('#numeroCartellaEsattoriale', '0000000000000000')
      .setValue('#totaleRiscossione', '123.10')
      .click('#discaricoAmministrativo')
      .click('#discaricoAmministrativo-totale')
      .click('#mancanzaPresupposto')
      .waitForElementVisible('#stepAvanti', 500)
      .click('#stepAvanti')
      .waitForElementVisible('#tipoTitolo', 500)
      .assert.containsText('#tipoTitolo', 'CARTELLA: N° 000000000000')
      // .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 20/12/1900') TODO impostare con i click
      .assert.containsText('#importoTotale', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      .assert.containsText('#oggettoDomanda > div > div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('#motivoDomanda > div > div', 'MANCANZA DEL PRESUPPOSTO')
      .waitForElementVisible('#email', 1000)
      .setValue('#email', 'daniel.scaletta@consulenti.csi.it')
      .useXpath()
      .click('//*[@id="informativa-privacy"]/div/div/div/div/div/div/div[1]/label')
      .useCss()
      .moveToElement('#inviaRichiestaDTE', 2, 2)
      .saveScreenshot('test/e2e/reports/invia_richiesta_dte.jpg')
      .click('#inviaRichiestaDTE')
      .waitForElementVisible('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(2) > div > div:nth-child(1) > div > div > div.v-alert__content > div > div.bodyAlertDark.col-md-10.col-12 > div > p:nth-child(2) > strong', 500)
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(2) > div > div:nth-child(1) > div > div > div.v-alert__content > div > div.bodyAlertDark.col-md-10.col-12 > div > p:nth-child(1) > strong', 'La domanda è stata registrata correttamente.')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(2) > div > div:nth-child(1) > div > div > div.v-alert__content > div > div.bodyAlertDark.col-md-10.col-12 > div > p:nth-child(2) > strong', 'N° di protocollo 00000139/2020')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'ANTONIO MAMMARELLA GIARDINIERI')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: MMMNTN68A16C632X')
      .assert.containsText('//*[@id="sesso"]', 'SESSO: M')
      .useCss()
      .assert.containsText('#titoloEsecutivo > h2', 'Titolo esecutivo: ingiunzione')
      .useXpath()
      .assert.containsText('//*[@id="tipoTitolo"]', 'INGIUNZIONE: N° S116000210420')
      // .assert.containsText('#dataNotifica', 'DATA DI NOTIFICA: 08/01/2020')
      .assert.containsText('//*[@id="importoTotale"]', 'IMPORTO TOTALE RISCOSSIONE: 123,10 €')
      .assert.containsText('//*[@id="oggettoDomanda"]/div/div/div', 'CHIEDO IL DISCARICO AMMINISTRATIVO TOTALE')
      .assert.containsText('//*[@id="pagamentoEseguito"]', 'PAGAMENTO ESEGUITO')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div[2]/div/div[7]/p[1]', 'daniel.scaletta@consulenti.csi.it')
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div/div/div[2]/div/div[8]/div[1]/button/span', 'STAMPA RIEPILOGO')
      .useCss()
      .end()
  }
}
