// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage
// https://github.com/nightwatchjs/nightwatch-docs

module.exports = {
  'default e2e tests': function (browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL

    browser
      .url(devServer + '/#/bollo/pago')
      .waitForElementVisible('#cercaIuvBtn > span', 1000)
      .setValue('input[id=iuv]', '201911150000002785277113')
      .click('#cercaIuvBtn > span')
      .waitForElementVisible('#boxEsitoRicerca > div:nth-child(1) > div > dl.text-center.col-6.col-sm-4.offset-sm-2 > dd > strong', 2000)
      .assert.containsText('#boxEsitoRicerca > div:nth-child(1) > div > dl.text-center.col-6.col-sm-4.offset-sm-2 > dd > strong', '438,77 €')
      .assert.containsText('#boxEsitoRicerca > div:nth-child(1) > div > dl:nth-child(2) > dd > strong', '10/2015')
      .assert.containsText('#boxEsitoRicerca > div:nth-child(2) > table > tr:nth-child(1) > td', '408,93 €')
      .assert.containsText('#boxEsitoRicerca > div:nth-child(2) > table > tr:nth-child(2) > td', '24,54 €')
      .assert.containsText('#boxEsitoRicerca > div:nth-child(2) > table > tr:nth-child(3) > td', '5,30 €')
      .assert.containsText('#boxEsitoRicerca > div:nth-child(2) > table > tr:nth-child(4) > td > strong', '438,77 €')
      .useXpath()
      .assert.containsText('//*[@id="denominazione"]', 'EVENEPOEL REMCO')
      .assert.containsText('//*[@id="codFiscale"]', 'CF: REXLNZ46A30C048F')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[1]', 'AUTOVEICOLO')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[2]', 'TARGA: DV720BS')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[3]', 'SCADENZA: 10/2015')
      .assert.containsText('//*[@id="dati-veicolo"]/div/div/div[5]', 'IMPORTO: 408,93 €')
      .useCss()
      .click('#boxEsitoRicerca > div.action-button-wide.row > div.col-md-6.text-md-right > a.v-btn.v-btn--has-bg.v-btn--router.theme--light.v-size--default.primary > span')
      .waitForElementVisible('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > h2', 2000)
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > h2', 'Dati veicoli e composizione importo')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > div:nth-child(2) > div > div > button > div.row > div:nth-child(2) > div > strong:nth-child(1)', 'CF: REXLNZ46A30C048F')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > div:nth-child(2) > div > div > button > div.row > div:nth-child(2) > div > strong:nth-child(3)', 'Targa: DV720BS')
      .click('#vaiAlPagamentoBtn > span')
      .assert.containsText('#riferimentiPraticaPago > div:nth-child(4) > div > div > div > div.v-text-field__details > div > div > div', 'L\'indirizzo e-mail è obbligatorio.')
      .setValue('input[id=email]', 'remco.evenepoel@wolfpack.com')
      .click('#riferimentiPraticaPago > div.inner-cont-2box.info-left.row > div > div > div > div.position-relative.d-inline-block > div > div > div.v-input__slot > label')
      .click('#vaiAlPagamentoBtn > span')
      .useXpath()
      .waitForElementVisible('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div/div[2]/div/div/strong', 1000)
      .assert.containsText('//*[@id="main-content"]/div/div[1]/div[2]/div[1]/div/div/div[2]/div/div/strong', 'Il pagamento viene effettuato sulla piattaforma pagoPA.')
      .useCss()
      .click('#backButton')
      .waitForElementVisible('#aggiungiPagamentoBtn > span', 1000)
      .click('#aggiungiPagamentoBtn > span')
      .waitForElementVisible('#riepilogoCarrelloBtn', 1000)
      .useXpath()
      .click('//*[@id="main-content"]/div/div[1]/div[2]/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div[3]')
      .useCss()
      .pause(500)
      .click('#calcolaBtn')
      .setValue('#codiceFiscale', 'REXLNZ46A30C048F')
      .setValue('#targa', 'DV720BS')
      .setValue('input[id="tipoVeicolo"]', 'A')
      .click('#calcolaBtn > span')
      .waitForElementVisible('#boxErrDiv > div > div > div.v-alert__content > div > div.col-md-10.col-12 > p', 1000)
      .assert.containsText('#boxErrDiv > div > div > div.v-alert__content > div > div.col-md-10.col-12 > p', 'Pagamento già presente, per eliminarlo andare al riepilogo')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp.tab-card-space > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > form > div:nth-child(1) > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .click('#main-content > div > div:nth-child(1) > div.container > div.col-lg-10.mx-lg-auto > div > div.tab-content-hp.tab-card-space > div > div.v-window.noauthService.v-item-group.theme--light.v-tabs-items > div > div.v-window-item.v-window-item--active > div > form > div:nth-child(2) > div > div.v-input__slot > div.v-input__append-inner > div > button')
      .setValue('input[id=codiceFiscale]', 'VRTWTO46A30C048F')
      .setValue('input[id=targa]', 'KV720AB')
      .click('#calcolaBtn > span')
      .waitForElementVisible('#boxEsitoRicerca > div:nth-child(1) > div > dl.text-center.col-6.col-sm-4.offset-sm-2 > dd > strong', 1000)
      .assert.containsText('#boxEsitoRicerca > div:nth-child(1) > div > dl.text-center.col-6.col-sm-4.offset-sm-2 > dd > strong', '438,77 €')
      .assert.containsText('#dati-anagrafici-intestatario > h2', 'Dati anagrafici proprietario')
      .saveScreenshot('test/e2e/reports/dettaglio_pagamento.jpg')
      .useCss()
      .click('#boxEsitoRicerca > div.action-button-wide.row > div.col-md-6.text-md-right > a.v-btn.v-btn--has-bg.v-btn--router.theme--light.v-size--default.primary > span')
      .waitForElementVisible('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > div.cardTotale.space-section > div > p', 500)
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > div:nth-child(2) > div > div:nth-child(2) > button > div.row > div:nth-child(1) > div > span', '2')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > div:nth-child(2) > div > div:nth-child(2) > button > div.row > div:nth-child(2) > div > strong:nth-child(1)', 'CF: VRTWTO46A30C048F')
      .assert.containsText('#main-content > div > div:nth-child(1) > div.container > div > div > div:nth-child(3) > div > div:nth-child(2) > div > div:nth-child(2) > button > div.row > div:nth-child(2) > div > strong:nth-child(3)', 'Targa: KV720AB')
      .click('#vaiAlPagamentoBtn')
      .click('#transazionePagoPaBtn')
      .saveScreenshot('test/e2e/reports/transazionePagoPa.jpg')
      .end()
  }
}
